### ISSUE TITLE
Persona integration

### ISSUE THREAD

**Issue by fernandoacorreia** [mohiva/play-silhouette#108]
Consider supporting [Persona](https://developer.mozilla.org/en-US/Persona/Why_Persona).

**Comment by miroslavhornak** [comment]
Persona is no longer actively developed by Mozilla. Mozilla has committed to operational and security support of the persona.org services until November 30th, 2016.

On November 30th, 2016, Mozilla will shut down the persona.org services. Persona.org and related domains will be taken offline.

If you run a website that relies on Persona, you need to implement an alternative login solution for your users before this date.

For more information, see this guide to migrating your site away from Persona:

https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers

**Comment by akkie** [comment]
Thanks for the info!

**Comment by akkie** [comment]
And for the donation :+1:
