### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by stephenmuss** [mohiva/play-silhouette#190]
Unfortunately at the moment the lack of documentation is a huge barrier to using Silhouette. To even start understanding requires browsing the wiki, looking at activator templates and a lot of digging through the source code.
It would be great to have comprehensive documentation which outlines everything in one place.

**Comment by akkie** [comment]
I think the documentation is really good at this time. Based on the suggestions by @hwu I've created an issue for the seed template.

Thanks for your suggestions and your interest in Silhouette. 2.0 is near (o;
