### ISSUE TITLE
Add CAS (Central Authentication Server) support

### ISSUE THREAD

**Issue by bwbecker** [mohiva/play-silhouette#198]
As discussed (briefly) in the Google Group, I need support for CAS.  I've implemented the protocol before, but have struggled with integrating it into the Play framework in an acceptable way.  Silhouette looks like an ideal way to do that!

Help and guidance appreciated!

**Comment by akkie** [comment]
@bwbecker Any news on this? I would like to release the 2.0 in the next few days.

**Comment by bwbecker** [comment]
Christian —

Thanks for the poke.  Unfortunately, I’ve had a number of projects come out of the woodwork and haven’t gotten to this yet.  It’ll happen, but not in time for 2.0.

Sorry,

Byron

> On Jan 18, 2015, at 6:51 AM, Christian Kaps <notifications@github.com> wrote:
> 
> @bwbecker <https://github.com/bwbecker> Any news on this? I would like to release the 2.0 in the next few days.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mohiva/play-silhouette/issues/198#issuecomment-70405191>.
> 


---------------------------------------------
Byron Weber Becker
School of Computer Science
University of Waterloo, Waterloo, Ontario  N2L 3G1
Email: bwbecker@uwaterloo.ca
Phone:  519-888-4567 x34661
Fax:  519-888-4380 (include my email on cover page)

Advising FAQ:  www.cs.uwaterloo.ca/current/faq

**Comment by akkie** [comment]
It's all good. Let me know if you can find the time.

**Comment by akkie** [comment]
Fixed with #450
