### ISSUE TITLE
Silhouette's logging config can override local project logging config

### ISSUE THREAD

**Issue by tkaiser** [mohiva/play-silhouette#238]
See play.api.Logger#configure: the order in which logging files are checked on the classpath is
1. "application-logger.xml"
2. "logger.xml"
3. "logback.xml"

If the client application uses "logger.xml" as name for the local logging config, this config will get overridden by the silhouette config, since that one is called "application-logger.xml".
If the client renames its logging config to "application-logger.xml" too, things will work as expected again.

This took me some time and debugging to figure out why my logs weren't showing up anymore. I will try to create a pull request on the weekend, if anyone wants me to.

**Comment by akkie** [comment]
Fixed with #249
