### ISSUE TITLE
CredentialsProvider doesn't play well with default Silhouette.exceptionHandler

### ISSUE THREAD

**Issue by Firfi** [mohiva/play-silhouette#242]
Thing is on nonexist user it throws AccessDeniedException 

  new AccessDeniedException(CredentialsProvider.UnknownCredentials.format(id))

which exceptionHandler converts into 403 Forbidden status later in the flow that should be actually 401 as there's _no_ user which we deny access yet.

Controller code looks somewhat like this:

  ... case Some(p: CredentialsProvider) =>  p.authenticate(credentials) ...
  .flatMap(blahblah)
  ).recoverWith(exceptionHandler)

**Comment by Firfi** [comment]
@akkie thanks for the answer. Actually I don't need fix immediately, but will send pull request anyway, just because I can. I found nothing better though than just change AccessDenied stuff to AuthenticationException. By the way, why use exceptions at all? They're for pussies. Maybe it'd be better to use some Try or Either?

**Comment by akkie** [comment]
Try is already used inside Futures to handle errors. And this error handling works with exceptions. So there is no need for another error handling mechanism.

Thanks for the pull request
