### ISSUE TITLE
Parameterize `LoginInfo`

### ISSUE THREAD

**Issue by guersam** [mohiva/play-silhouette#267]
Hi,

It's not a strong requirement but just for discussion.

Currently `LoginInfo` accepts `String` for either provider id and the unique key, but I usually prefer defining each provider as a dedicated case object with extends `AuthProvider` marker trait. So I'd like to ask if it makes sense to parameterize `LoginInfo`. The key also can be parameterized, but I'm not sure because narrowing key type can harm forward compatibility. 

props:
 - More type safety, hence less error-prone

cons:
 - Specifying type parameters in outer classes might be bothering

What do you think?

**Comment by akkie** [comment]
Please could you be a bit more specific. Maybe with a code snippet?

**Comment by guersam** [comment]
Ok, I'm evaluating silhouette for a webapp prototype which supports social login. I'll enrich this issue when I have more detailed use case.

**Comment by guersam** [comment]
Playing with some seed projects, I realized that there aren't that much time to deal with provider id by myself, hence I'll close this one. Sorry for the noise!
