### ISSUE TITLE
How to reset password?

### ISSUE THREAD

**Issue by yujing5b5d** [mohiva/play-silhouette#278]
Hello,
     I am new to use this silhouette. Thanks for your great work and I quite appreciate these code.
     In current , I am trying to implement a function to 'reset password'.
     In my mind, I'd like to get his old password, check and set a new one, but it seems a bit too hard.
     Code as follow... 
```
def updatePasswordByOldPassword = Action.async(parse.json) { implicit request =>
  request.body.validate[UpdatePasswordForm.UPFData].map { data =>
    val loginInfo = LoginInfo(CredentialsProvider.ID, data.identifier)
    userService.retrieve(loginInfo).flatMap {
      case Some(user) =>
        val authInfo = passwordHasher.hash(data.token)
        IOUserService.getAuth(data.identifier) match {
          case Some(oldAuth) => {
            val pass: PasswordInfo = PasswordInfo(oldAuth.hasher, oldAuth.pass, oldAuth.salt)
            val oldPassword: String = data.password
            if (true) { //TODO: How can I check his password?
              // or, how can I compare 'oldPassword' with 'pass' ?
              for {
                authInfo <- authInfoService.save(loginInfo, authInfo)
                authenticator <- env.authenticatorService.create(loginInfo)
                token <- env.authenticatorService.init(authenticator)
              } yield {
                env.eventBus.publish(SignUpEvent(user, request, request2lang))
                env.eventBus.publish(LoginEvent(user, request, request2lang))
                Ok(Json.obj("token" -> token))
              }
            } else {
              Future.successful(BadRequest(Json.obj("message" -> Messages("user.password_not_match"))))
            }
          }
          case _ =>
            Future.successful(BadRequest(Json.obj("message" -> Messages("user.password_not_found"))))
        }
      case None =>
        Future.successful(BadRequest(Json.obj("message" -> Messages("user.not_found"))))
    }

  }.recoverTotal {
    case error =>
      Future.successful(Unauthorized(Json.obj("message" -> Messages("invalid.data"))))
  }
}
```

Is it possible that to give some more suggestions ? Any reply are appreciated.

**Comment by misto** [comment]
Hi,

> Is it possible that to give some more suggestions ? Any reply are
> appreciated.

Take a look at the play-multidomain seed project, it also includes password 
reset:

https://github.com/adrianhurt/play-multidomain-auth/blob/master/modules/web/app/controllers/web/Auth.scala#L190

Regards

Mirko

-- 
Mirko Stocker | me@misto.ch
Work: http://ifs.hsr.ch | http://infoq.com
Personal: http://misto.ch | http://twitter.com/m_st

**Comment by akkie** [comment]
Hi, 

it's the same as in the [CredentialsProvider](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala#L66).

Cheers,
Christian

**Comment by yujing5b5d** [comment]
@akkie Thanks very much, I changed code as follow.
```
val pass: PasswordInfo = PasswordInfo(oldAuth.hasher, oldAuth.pass, oldAuth.salt)
val oldPassword: String = data.password
if (passwordHasher.matches(pass, oldPassword)) {
  // are follow lines right ? 
  for {
    authInfo <- authInfoService.save(loginInfo, authInfo)
    authenticator <- env.authenticatorService.create(loginInfo)
    token <- env.authenticatorService.init(authenticator)
  } yield {
    env.eventBus.publish(SignUpEvent(user, request, request2lang))
    env.eventBus.publish(LoginEvent(user, request, request2lang))
    Ok(Json.obj("token" -> token))
  }
} else {
  Future.successful(BadRequest(Json.obj("message" -> Messages("user.password_not_match"))))
}
```

+ We only use `bcrypt` as hasher and is just use passwordHasher directly ok ?
+ We wish to update user's password , is that event process ok ?

Thanks for your reply again.

**Comment by yujing5b5d** [comment]
@misto 
Thanks for your suggestion

**Comment by akkie** [comment]
If the user is logged in when he tries to change the password? If yes then it isn't needed to create a new authenticator. Silhouette itself doesn't listen for events. So it's up to you to decide if an event is useful or not.
