### ISSUE TITLE
JWTAuthenticator invalid with default settings

### ISSUE THREAD

**Issue by ploddi** [mohiva/play-silhouette#283]
Seems like `JWTAuthenticator` always invalid when `JWTAuthenticatorSettings.authenticatorIdleTimeout` is `None` (default setting).

**Comment by akkie** [comment]
Hi, thanks for taking the time to write this bug report. But can you be a bit more specific?

If you take a look at the https://github.com/mohiva/play-silhouette-angular-seed project, then you can see that JWT authenticator is initialized with `authenticatorIdleTimeout = None`. And if you sign-in with the example, then the authenticator is valid. You can also look at the source of the [JWTAuthenticator](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala#L92). Here you can see that the authenticator can only be timed out if the `idleTimeout` is defined.

**Comment by ploddi** [comment]
Ah, my boolean logic skills is just bad. Never mind.

**Comment by akkie** [comment]
Thanks and no problem!
