### ISSUE TITLE
Maybe expose settings for ClefProvider?

### ISSUE THREAD

**Issue by igorbernstein** [mohiva/play-silhouette#285]
Hi,

How would you feel about exposing ClefProvider's OAuth2Settings as a field?

Currently, having to reference the current Play app in a view feels a bit awkward...
https://github.com/mohiva/play-silhouette-seed/blob/b752da/app/views/signIn.scala.html#L40

```scala
<div>
  @for(p <- providers if p.id != "clef") {
    <a href="@routes.SocialAuthController.authenticate(p.id)"><img src="@routes.Assets.at(s"images/providers/${p.id}.png")" style="width:60px;height:60px;"></a>
  }
</div>

<script type="text/javascript" src="https://clef.io/v3/clef.js" class="clef-button" data-app-id="@Play.configuration.getString("silhouette.clef.clientID").getOrElse("")" data-color="blue" data-style="flat" data-redirect-url="@Play.configuration.getString("silhouette.clef.redirectURL").getOrElse("")" data-type="login"></script>
```

If you exposed the settings, then the code can be improved a bit by:
- not needing the current play app
- allow for toggling clef via the environment like all other providers

Something along these lines:
```scala
@for(p <- providers) {
  @p match {
    case clef:ClefProvider => {
      <script type="text/javascript" src="https://clef.io/v3/clef.js" class="clef-button" data-app-id="@clef.settings.clientID" data-color="blue" data-style="flat" data-redirect-url="@clef.settings.redirectURL" data-type="login"></script>
    }
    case _ => {
      <a href="@routes.SocialAuthController.authenticate(p.id)"><img src="@routes.Assets.at(s"images/providers/${p.id}.png")" style="width:60px;height:60px;"></a>
    }
  }
}
```

**Comment by akkie** [comment]
I'm not sure about that. Let my quote myself from a [similar issue](https://github.com/mohiva/play-silhouette/issues/187#issuecomment-50263909):

>>This would violate against the [SOLID principles](http://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) which are a fundamental concept of object oriented design. Providing the `PasswordHasher` isn't the responsibility of the `CredentialsProvider`. If developers rely on this additional method and we decide to rename it or use other ways to define a password hasher then we brake the contract we have signed with the developers. I hope you understand this.

Replace `PasswordHasher` with `OAuth2Settings` and you have the same scenario.

I think it's currently a limitation of Play that the current application must be imported to access the configuration and not a design mistake of Silhouette. So I'm not sure if we should compensate this limitation with the changes you suggested. It seems that this limitation will also be fixed with Play 3.

What do you think?

**Comment by igorbernstein** [comment]
Thats a valid argument.  After some thought I realized that the api is fine as is, but the implementation in the seed is a bit off: the signIn template shouldn't be using the global app nor providers map directly..instead the action/controller should be passing in a collection provider description objects that contain all the info necessary to render the list.  The controller, in turn should have those description objects injected into it.

**Comment by akkie** [comment]
If you find a good implementation, then I would be happy if you could create a pull request.
