### ISSUE TITLE
Arbitrary claims in JWT token

### ISSUE THREAD

**Issue by Kyprus** [mohiva/play-silhouette#290]
You are supposed to be able to add arbitrary data (claims) to a JWT token on creation. From what I can tell the lib silhouette is using to build the JWTs supports this but there is no way to pass the information to the authenticator. Is something that could be supported? Thanks!

**Comment by akkie** [comment]
The JWT authenticator is only design for authentication purpose. So only authentication specific data should be stored inside the token. If you need other data on client side, then you should issue a new JWT which has nothing to do with the authentication process. What kind of data would you transport in the token?

**Comment by Kyprus** [comment]
I'm implementing something CAS-like using JWTs. So when authenticating a user I'd like to encode the user's roles in the JWT so other services can perform authorization.

**Comment by akkie** [comment]
I'm not sure if we should allow to pass arbitrary data to the authenticator create method. The first reason is that all authenticators share the same interface. And it makes no sense to allow to add data to the other authenticators. The second reason is that the authenticators are also created [directly from Silhouette core](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala#L243) if an request providers was used for authentication.

Maybe we could add a new optional property(holding a Json object) to the authenticator which can then be set later after authenticator creation. If then the authenticator gets initialized, we could add this data to the JWT.

Something like this:

```scala
case class JWTAuthenticator(
  id: String,
  loginInfo: LoginInfo,
  lastUsedDate: DateTime,
  expirationDate: DateTime,
  idleTimeout: Option[Int],
  jsonData: Option[JsObject] = None) extends StorableAuthenticator {
```

@rfranco What do you think?

**Comment by rfranco** [comment]
@akkie I think the JWT Authenticator should be design only for authentication purpose as you said. Anyway it's possible extends that and customize the default behavior.

**Comment by diwalak** [comment]
+1 for the optional json data.
Sending back the list of roles is a very common pattern. It will be painful if we had to jump through the hoops to achieve it.

**Comment by studiodev** [comment]
+1 too, roles or scopes are frequently used with JWT (even if I can't say if it's a good practice or not).
