### ISSUE TITLE
Allow multiple redirectURL for one provider.

### ISSUE THREAD

**Issue by hanfeisun** [mohiva/play-silhouette#296]
In the OAuth2Settings, there is a field called redirectURL, which points to the URL after a successful authentication on the OAuth provider. `

However, sometimes I have two front-end sites (`test-site1` and `test-site2`) using the same play-silhouette back-end application. They will send silhouette different `redirectURL` value in the AJAX call. But currently, silhouette seems to only allow one redirectURL..

I was wondering whether there is a way to allow multiple redirectURL in OAuth2Settings..

**Comment by akkie** [comment]
This is currently not possible. The problem is that the dependencies, based on the chosen DI approach, will be wired either on compile time or on application start. So there is no change to chose the `redirectURL` based on the request. And I've currently no idea how this can be implemented without affecting the other 99,9 percent of the users which haven't such a use case.

Any suggestions?

**Comment by hanfeisun** [comment]
Or is there a way to allow redirectURL to any sites by setting redirectURL to `*`..

I know this may be super unsafe, but it is ok to use it in an internal testing environment..

**Comment by hanfeisun** [comment]
As I understand, silhouette doesn't have to know the `redirectURL` during compile stage or on application start because `redirectURL` is already included as a field in the AJAX request body to `authenticate/:provider`.. Is this true?

**Comment by akkie** [comment]
Yes, in your special case or with the use of Satellizer this may be true. But this isn't the default case.

I think if we implement such a feature then the application could be vulnerable. Please see:
http://security.stackexchange.com/questions/44214/what-is-the-purpose-of-oauth-2-0-redirect-uri-checking
http://homakov.blogspot.de/2013/03/oauth1-oauth2-oauth.html

A quote from the last link under the point Vector 2:
> redirect_uri should be a constant value in application settings.

**Comment by hanfeisun** [comment]
I agree that it will lead to be vulnerable. And this issue may be worked around by setting two different `redirectURL` in different `.conf` file.

but I still think it will be better if developer are able to make authentication easier in development environment by setting it to `*` if they know clearly what they are doing.. Just like `Access-Control-Allow-Origin: *` field in HTTP header.

**Comment by akkie** [comment]
If you set the redirectURL to `*` then the provider would not know where it should redirect to. So this wouldn't work.

I think at this moment the only solution would be to create different environments with different controllers and different configurations. Each for every redirect URL.

In the next version we could allow to override the global config on a per request base. Maybe in 2.1.

**Comment by hanfeisun** [comment]
maybe you're right.. I will use different environment as the solution :-)

**Comment by igorbernstein** [comment]
I hope you don't mind if I butt in here, but I'm working on #304 and this seems to be the more general issue...

@hanfeisun Would you mind clarifying if the 2 sites are on the same subdomain and just have different root paths (ie. www.example.com/test-site1 ) or do they live on different domains (ie. test-site1.example.com)?

If they live on the same subdomain, you can create a preauthenticate action in your SocialAuthController that sets a session key  for the destination url before redirecting into the oauth flow. Then upon completing the oauth flow, you can pull out the session key, (validate it to prevent an open redirect), then redirect to the appropriate place.

However if the domains differ, then it gets closer to what I'm playing around with on #304...I don't think allowing the redirectURL to be configured per request would be enough. Unless I'm mistaken, almost all OAuth 1 & 2 providers allow only a single domain per consumerKey/consumerSecret & clientId/clientSecret.  So you would need to allow those fields to be configureable per request as well.  With that in mind, I think #304 would be a half measure while implementing dynamic provider settings would be the ideal.

@akkie Would it be desirable for the SocialProvider subclasses to take a ```*Settings``` factory method ```(implicit request:RequestHeader) -> *Settings``` as opposed to the ```*Settings``` instances themselves?  This way, the settings could be computed per request? And as a followup, is it too late in the release cycle for such a big change in api?

ps. ```*Settings``` = ```OAuth1Settings```, ```OAuth2Settings```, ```OpenIdSettings```

**Comment by igorbernstein** [comment]
Additional we can provider an implicit converter ```settings2factory``` that can convert an instance of *Settings into a ```(RequestHeader -> *Settings)``` function.  But I don't have enough scala experience to know if that would be frowned upon.

ps. if you think this good way forward, I can close #304 & put together a proper PR for this by Tuesday evening.

**Comment by akkie** [comment]
@igorbernstein I think #304 should be a separate pull request.

To solve this issue, we should provide an additional method to allow to pass the settings per request because this feature is a corner case. For all other cases the lib should be configured globally. And if we find a proper solution, then it goes into 2.1.

Anyway, your settings factory proposal sounds interesting. But please let me some time to think about it.

**Comment by akkie** [comment]
Fixed with #354
