### ISSUE TITLE
JWTAuthenticator with memcached - "Key too long error"

### ISSUE THREAD

**Issue by jamesallchin** [mohiva/play-silhouette#297]
Hi, 

Wondering if someone can help. We're keen to use the JWTAuthenticator in Silhouette. However, using this approach on clustered server environment means we must distribute the Play framework caching layer so that the server side tokens are shared across servers. 

Following the guidance in the Silhouette docs, the easiest approach is to configure the default play framework cache layer to either memcached or redis. We decided on memcached for the moment.

Unfortunately, when using the JWTAuthenticator the token is too large too store and we get the following error:

[IllegalArgumentException: Key is too long (maxlen = 250)]

Now we do have control of our own authenticate method in the the CredentialsAuthController. So we could therefore hash this key to make it smaller, but from my understanding we wouldn't have the ability to modify the JWTAuthenticator class to change the way in which is pulls from the cache?

Is there a suitable workaround to this problem? I guess the only way would be for us to create our own equivalent Authenticator as the JWTAuthenticator but hash the tokens to make them smaller?

Thanks, 

James

**Comment by akkie** [comment]
Hi,

the [JWTAuthenticatorService](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala#L109) gets an [IDGenerator](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/util/IDGenerator.scala#L27) instance passed. By default in the seed templates the [SecureRandomIDGenerator](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/util/SecureRandomIDGenerator.scala#L35) will be used. So either you change the byte length of the `SecureRandomIDGenerator` or you implement your own ID generator.

Cheers,
Christian

**Comment by aparamonov** [comment]
Christian,

Can you base JWTAuthenticator on play's secret key instead of a random key to get rid of usage cache layer in this case?
I think this approach will require no additional actions for somebody who wants to setup cluster environment.

Thanks,
Alexey

**Comment by akkie** [comment]
@aparamonov In this case every authenticator would have the same ID. The other issue is that Play's secret can also be longer as 250 chars.

By default the `JWTAuthenticatorService` doesn't need a cache layer. And the problem exists with all other authenticators too because they use all the `SecureRandomIDGenerator` by default.

What's the problem with setting the byte length of the generated ID?

**Comment by akkie** [comment]
One thing I forgot to mention. The authenticators are not bound directly to the cache anymore, because the `AuthenticatorDAO` can be implemented with any backing store. In the previous version it was bound directly to the cache.

**Comment by akkie** [comment]
@jamesallchin Does my suggestions solve your issue? If yes, it would be nice if that issue could be closed. Or do you have further questions?

**Comment by jamesallchin** [comment]
@akkie Thanks Christian. It does solve the issue. Thanks. However, one last question before closing... You mentioned: 

"One thing I forgot to mention. The authenticators are not bound directly to the cache anymore, because the AuthenticatorDAO can be implemented with any backing store. In the previous version it was bound directly to the cache."

Do you have an example of this where the JWTAuthenticator is not bound to the cache? From what I can see in your example see templates they still use the cache?

**Comment by akkie** [comment]
The examples using the `CacheAuthenticatorDAO` because it is the default `AuthenticatorDAO` implementation and it works out of the box with the Play cache. But you can also create your own `AuthenticatorDAO` implementation, which uses a database as example.

**Comment by jamesallchin** [comment]
Thanks for all your help - let's close it.
