### ISSUE TITLE
It should be possible to avoid loading the user from the DB in every SecureAction request 

### ISSUE THREAD

**Issue by afrad** [mohiva/play-silhouette#307]
When calling a SecuredAction the LoginInfo gets retrieved and used to load the user from the db  [code](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala#L238). This makes this operation very costly. Especially when only the logininfo is needed. It should be allowed to decide to either load to the User or not during a secured request. Maybe using something like "SemiSecuredAction". I'm don't think this will have security issues.

**Comment by akkie** [comment]
What is the use-case for such a feature? Does it not be enough to use the authenticator service to retrieve the authenticator (which contains the login info) in a default action?

**Comment by afrad** [comment]
The use case I have is that, during a request, I just have to know that that user is logged in (using JWTAuthenticator  in my case). This is basically also a "SecuredAction" but without the need to retrieve the User from the DB. But you are right, using the default action could be enough.

**Comment by akkie** [comment]
One thing that doesn't work with my suggested solution, is to touch/update/renew/discard the authenticator, because this actions will be executed internally by the `SecuredAction` or `UserAwareAction`.

**Comment by afrad** [comment]
Thank you for mentionning that. I will consider it. I implemented the "SemiSecuredAction" composing with a standard Action and finised implementing a code similar to the your SecuredAction using ActionBuilder but without retrieving the User. I needed it because I retriebe the user id from the LoginInfo and use it to forward the request to the right Akka User Actor that could be still alive in the cluster.  
 
Here is my code
````Scala
object SemiSecuredAction extends SemiSecuredActionBuilder{
  def apply ( env: Environment[User, JWTAuthenticator]) = new SemiSecuredActionBuilder(env)
}
  case class SemiSecuredActionBuilder (env: Environment[User, JWTAuthenticator] = null )  extends  ActionBuilder[Request]{
  def invokeBlock[A](request: Request[A], block: (Request[A]) => Future[Result]): Future[Result] = {
    env.authenticatorService.retrieve(request).flatMap {
      case Some(a) if a.isValid => block(request)
      case None => DefaultActionHandler.handleForbidden(request)
    }
  }
}
````

**Comment by akkie** [comment]
So is this still an issue? Or can this issue be closed?
