### ISSUE TITLE
EventBus trait?

### ISSUE THREAD

**Issue by igorbernstein** [mohiva/play-silhouette#312]
Hi Christian,

I was wondering how you would feel about extracting out an EventBus trait that contained only the `publish(event: Event): Unit ` method, then using that trait in `Environment` and renaming the existing `EventBus` to `impl.util.AkkaEventBus`? The benefits of this change are:

- developers can plug in their own implementations based on other pubsub systems
- testkit can easily implement an empty `FakeEventBus` that doesn't require initializing & shutting down akka for every unit test
- `Environment` can be defined as the minimal set of dependencies needed by controllers with `SecuredAction`s

If this is something you'd be interested in I can put together a PR

**Comment by akkie** [comment]
Sounds good to me!

But what do you mean with "Environment can be defined as the minimal set of dependencies needed by controllers with SecuredActions"? Isn't this exactly so implemented?

**Comment by igorbernstein** [comment]
Ok, great! I should have something to show on Tuesday.

I just meant that all the Apis exposed by environment are very lean & geared for SecuredActions except for EventBus which adds unnecessary subscription functionality.
