### ISSUE TITLE
SecuredRequest type ???

### ISSUE THREAD

**Issue by ubourdon** [mohiva/play-silhouette#319]
The case class `case class SecuredRequest[B](identity: I, authenticator: A, request: Request[B]) extends WrappedRequest(request)` is defined in trait `com.mohiva.play.silhouette.api.Silhouette` .
If function need this type as parameter, what is the type of SecuredRequest ?
I mean `def myFunction[A,X](request: ???.SecuredRequest[A]): X` 
How can I use the type SecuredRequest in my code while is type depends on which context extends Silhouette trait ?

**Comment by akkie** [comment]
You should extract the values from this request and use it individually. If you need all data you could create an object which acts as a wrapper for the three single values.

The `SecuredRequest` exists only to transport additional data into an action. It's useless in another context.

**Comment by ubourdon** [comment]
Ok. Thx.
