### ISSUE TITLE
why embed a Future[Result]?

### ISSUE THREAD

**Issue by igorbernstein** [mohiva/play-silhouette#320]
https://github.com/mohiva/play-silhouette/blob/98cf59/silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala#L79

This isn't a big deal, I was just curious what was the use case for using a Future[Result] param here. Most of the time the result will be a simple redirect which doesn't require a future computation. In the off chance that the result does need to be computed asynchronously wouldn't the developer just add it as another line in the for comprehension before passing it to the embed?

Best,
Igor

**Comment by akkie** [comment]
Yes, I think for the parameter it can be a Result only. But for the return type it is needed because using the method in a for comprehension with other Futures, it must also return a Future. The idea was also that the user should be able to create an own authenticator service and do future related things in this method. The philosophy of Silhouette is it to cover the most thinkable use cases and to be extendable as possible. And why we are a reactive library, we try to use features everywhere, even if currently there is no need for a future.

Cheers,
Christian

**Comment by igorbernstein** [comment]
Sorry I should've been more clear, I'm specifically asking about the param not the return type. Can you clarify if this:

> we try to use features everywhere, even if currently there is no need for a future

applies to the param or only to the return? If it's only for latter, should I open a pr to drop the future from the param list? Or is it not worth it?

**Comment by akkie** [comment]
I'm not really sure about that. What if a user computes the result inside a Future? Then he must flatMap the Future so that he can pass the Result as argument to the embed method. And then inside the embed method we must create a new Future to wrap the result. I think it is better to hook into the Future a user passes, instead of creating a new one.

**Comment by igorbernstein** [comment]
this won't make a big difference one way or the other. It's either an extra future.successful wrapper or an extra flat map in the client code. And one less flat map in silhouette code if you take my suggestion.




The only point I'm trying to make is that current silhouette code is doing extra work to optimize for a less common use case and makes things slightly less readable for a more common use case.




But as I said, this isn't a huge hurdle...just something I noticed while trying to use the library.

**Comment by akkie** [comment]
> The only point I'm trying to make is that current silhouette code is doing extra work to optimize for a less common use case and makes things slightly less readable for a more common use case.

Please could you outline this a bit more?

**Comment by igorbernstein** [comment]
Currently, common client code has to explicit wrap the result in a future that the silhouette immediately unwraps.  The extra work comes from unwrapping something that usually doesn't need to be wrapped in the first place.  As I mentioned, this isn't a big deal, just odd that the common case requires this.  See below for examples

### Current implementation

silhouette code (from SessionAuthenticationService):
```scala
def embed(session: Session, result: Future[Result])(implicit request: RequestHeader) = {
    result.map(_.addingToSession(session.data.toSeq: _*))
  }
```

client code for the common case (from seed)
```scala
for {
  // ...
  result <- env.authenticatorService.embed(value, Future.successful(
    Redirect(routes.ApplicationController.index())
  ))
  // ...
```

client code for the less common use case:
```scala
for {
  // ...

  result <- env.authenticatorService.embed(value, generateAsyncResult())
  // ...
```

### Proposed implementation
silhouette code:
```scala
def embed(session: Session, result: Result)(implicit request: RequestHeader) = {
    result.addingToSession(session.data.toSeq: _*)
  }
```

client code for the common case
```scala
for {
  // ...
  result <- env.authenticatorService.embed(value, 
    Redirect(routes.ApplicationController.index())
  )
  // ...
```

client code for the less common use case:
```scala
for {
  // ...
  unwrappedResult <- generateAsyncResult()
  result <- env.authenticatorService.embed(value, unwrappedResult)
  // ...
```

**Comment by akkie** [comment]
I'm OK with your suggestion!

**Comment by igorbernstein** [comment]
I'll post the PRs for this & the seeds over the weekend.

**Comment by akkie** [comment]
OK, nice!
