### ISSUE TITLE
Convenience authenticate(LoginInfo) method for authenticators

### ISSUE THREAD

**Issue by igorbernstein** [mohiva/play-silhouette#324]
I was wondering how you'd feel about adding a convenience method to create/init/embed an authenticator into a Result? I've read #234 & [SO post](http://stackoverflow.com/questions/27417061/reaching-jwt-token-in-play2-silhouette-jwtauthenticator).  And I understand your goal to make Silhouette as flexible as possible, but it would nice to cut down on the verbosity for the average use case...how would you feel about adding the following to the Authenticator trait?

```scala
def authenticate(loginInfo: LoginInfo, result:Result[B]):Future[Result[B]] = {
  for {
    authenticator <- create(loginInfo)
    value <- init(authenticator)
    result <- embed(value, result)
  } yield result
}
```

**Comment by igorbernstein** [comment]
or maybe pimping Result to the method `withAuthenticatedLoginInfo` that takes the Authenticator as an implicit?

**Comment by akkie** [comment]
The SO post you reference, shows that embedding the authenticator in the result is a problem. Same with #325. The `renew` method does the same and if a user needs the authenticator in body he must implement the logic manually.

We could add two methods. One embedding it and the other returning the value.

```scala
def authenticate(loginInfo: LoginInfo, result:Result): Future[Result]
def authenticate(loginInfo: LoginInfo): Future[Value]
```

But I think the `retrieve` method should also be called.

```scala
def authenticate[B](result:Result)(implicit request: Request[B]): Future[Result]
def authenticate[B](implicit request: Request[B]): Future[Value]
```

**Comment by igorbernstein** [comment]
I don't quite understand what you mean. Would you mind clarifying and showing an example?

I'm not trying to add functionality here...just some syntactic sugar for the following use case exhibited here: 

- https://github.com/mohiva/play-silhouette-seed/blob/e50e81f0f79b62e54733434695abb5803e4217eb/app/controllers/CredentialsAuthController.scala#L45-L47
- https://github.com/mohiva/play-silhouette-seed/blob/e50e81f0f79b62e54733434695abb5803e4217eb/app/controllers/SocialAuthController.scala#L44-L48
- https://github.com/mohiva/play-silhouette-seed/blob/e50e81f0f79b62e54733434695abb5803e4217eb/app/controllers/SignUpController.scala#L65-L69

**Comment by akkie** [comment]
OK, I've misinterpreted your code. I've read `authenticate` and I've thought that the retrieval of the authenticator from request, must also be a part of this authentication process because this is what happens on a request. A user authenticates with an authenticator stored client side. Something like this:

```scala
def authenticate[B](result:Result)(implicit request: Request[B]): Future[Result] = {
  for {
    authenticator <- retrieve
    value <- init(authenticator)
    result <- embed(value, result)
  } yield result
}

def authenticate[B](implicit request: Request[B]): Future[Value] = {
  for {
    authenticator <- retrieve
    value <- init(authenticator)
  } yield value
}
```

So I would be open to it to add your suggested method, but I think the name is a bit unsuited.

**Comment by igorbernstein** [comment]
> def authenticate[B](result:Result)(implicit request: Request[B])

This doesn't help with the use case I'm trying to address...those 3 controllers need a way to embed a new LoginInfo.  The commonality of all those controllers is that they need to go outside the standard retrieve/renew/embed flow, so retrieve is detrimental.  I just want a simple way way to register & login a user w/o exposing all the internals of silhouette.

> def authenticate[B](implicit request: Request[B]): Future[Value]

The only use I can think for this method is to address the SO question earlier.  I don't think there is a need to add syntactic sugar for that use case....its a very uncommon use case...most users will just use the header in their authenticating client.  And if they want to embed it elsewhere they can drop down to the lower level methods of init/embed/etc.

>  the name is a bit unsuited.

Agreed, the method name needs to be improved.  Would it be possible/confusing to overload embed to 
accept a LoginInfo as well as AuthenticatorService#Value?

**Comment by akkie** [comment]
The name embed won't work, because as I pointed out above, we need two versions of the method. One that will embed the authenticator into the result and one which returns only the authenticator value.

```scala
def authenticate(loginInfo: LoginInfo, result:Result): Future[Result]
def authenticate(loginInfo: LoginInfo): Future[Value]
```

In mobile applications, most users tend to embed the authenticator value into the response body instead of the header. @see #234 #325

**Comment by igorbernstein** [comment]
Lets wait until #323 is done before addressing this issue...I'll try think of better method names in the interim

**Comment by akkie** [comment]
What do you think of a more common name like process?

**Comment by igorbernstein** [comment]
I hate generic names like that...I think overloading embed to take a LoginInfo will be good for my use case.

For your use case...can we just add an accessor to AuthenticatorResult that exposes the embedded Authenticator and/or Value?

In either case I don't think the methods should be named the same...

**Comment by akkie** [comment]
The use case for the second method results from your proposal. If we do not implement such a method, then we do not need a second method which returns the value instead of embedding it. All other scenarios can be handled with the current authenticator service implementation. Can this issue then be closed?

**Comment by igorbernstein** [comment]
I'm not quite sure what you mean...adding the higher level method embed(LoginInfo) doesn't take anything away, so shouldn't require any extra functionality.  

But this such a superficial change that I feel like I'm just wasting your time discussing it.  You can close this issue if you don't see it as useful addition.

**Comment by akkie** [comment]
I thought we agreed that we need two methods. One that replaces [this three lines](https://github.com/mohiva/play-silhouette-seed/blob/master/app/controllers/SignUpController.scala#L65-L67) in the seed template and one that replaces [this two lines](https://github.com/mohiva/play-silhouette-angular-seed/blob/master/app/controllers/SignUpController.scala#L61-L62) in the angular seed template?

We could implement it if we find a proper name. But as you said in another issue, such a method would only save some keystrokes and I'm not sure if it's worth.

**Comment by igorbernstein** [comment]
Ok, let's just drop it
