### ISSUE TITLE
Is there a way to add a jwt in response body on renew?

### ISSUE THREAD

**Issue by sedovalx** [mohiva/play-silhouette#325]
I'm looking for a way to add renewed token to the body of the action response like it is done in the authenticate action handler in [play-silhouette-angular-seed](https://github.com/mohiva/play-silhouette-angular-seed/blob/master/app/controllers/CredentialsAuthController.scala) example. 

Implementation like this doesn't help - there is token in the header but not in the body:

    def renew = SecuredAction.async { request =>
      request.authenticator.renew(Future.successful(Ok))
    }

May be I can do the same directly:
* retrive the authentificator by loginInfo
* discard it
* generate a new one
* embed it into header
* put in into body

Is it correct? Thank you!

**Comment by akkie** [comment]
Yes, you could do the same directly. But this does currently not work because the access to discard is restricted. We work on a solution. Please follow #323

**Comment by sedovalx** [comment]
Thank you!
