### ISSUE TITLE
rename renew -> replace

### ISSUE THREAD

**Issue by igorbernstein** [mohiva/play-silhouette#328]
This is extracted from https://github.com/mohiva/play-silhouette/pull/323/files#r27726793 ...how would you feel about renaming renew to replace? Its very easy to confuse renew with touch

**Comment by akkie** [comment]
I think `replace` is the wrong term here. The term `refresh` is much better in this context. A JWT as example cannot be replaced, the authenticator service returns a new/refreshed token with a new expiration time.

**Comment by igorbernstein** [comment]
From the perspective of the request the token has been replaced

**Comment by akkie** [comment]
With this method you can reissue a new refreshed/renewed token. It needn't be embedded into the response header. It can also be contained in the response body.

[This method](https://github.com/akkie/play-silhouette/blob/authenticator-result/silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala#L207) doesn't embed nothing. It returns only a new serialized representation of an authenticator.

[This method](https://github.com/akkie/play-silhouette/blob/authenticator-result/silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala#L195) might replace the authenticator in the response, but its main purpose is to refresh/renew the expiration of an authenticator as described [here](https://auth0.com/blog/2014/01/27/ten-things-you-should-know-about-tokens-and-cookies/#token-expiration).

**Comment by igorbernstein** [comment]
The first  method took me a bit by surprise...I didn't notice its inclusion in #323. I was primarily referring to the second (original) method...Its just a bit hard to tell it apart from touch
