### ISSUE TITLE
Reset password using angular + play

### ISSUE THREAD

**Issue by dsanchez31** [mohiva/play-silhouette#333]
Hi,

I'm using the 2.0-RC2 version on my play web app (angular for the ui and play for the backend).

But how to handle password change ?

AuthInfoService has no update method. 
Should I access directly on my passwordDAO to update it ?

How can invalidate old JWTAuthenticator token ?

Thanks

**Comment by akkie** [comment]
Currently it's the same as with the [CredentialsProvider](https://github.com/mohiva/play-silhouette/blob/2.0-RC2/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala#L69). In your `save` method you can determine which method on the DAO should be executed. [This issue](https://github.com/mohiva/play-silhouette/issues/326) tries to solve exactly this API inconsistencies.

> How can invalidate old JWTAuthenticator token?

Please could you be a bit more specific here? Do you store the tokens in a backing store? When do you plan to invalidate the tokens?

P.S. This is not really an issue. It would be nice if you could use the mailing list for such questions. Thanks for your understanding.

**Comment by dsanchez31** [comment]
Sorry, you are completly right, it is not an issue.

My first problem was that PassordInfoDAO is based on a mongo db. And as my PasswodInfo has no _id, the mongo.save always perform an insert. So I change the PasswordInfoDAO.save method to check if I need to insert or update.

My second problem is how to update the JWT token with a new one (and then invalidate old JWT token) when the user has changed its password to force him to reconnect.
I'm using CacheAuthenticatorDAO that creates a new token (and then keeping the last token valid)... Maybe I 'm doing something wrong... Moreover, I plan to use a JWT Authenticator DAO based on a mongo db. But JWTAuthenticator id field is not a BSONObjectId so I need to adapt the code...

Thanks

**Comment by akkie** [comment]
The `_id` field in a MongoDB must not be a BSONObjectID. It can also be the authenticator ID. For your other case you could use the `renew` method of the authenticator. This creates a new and invalidates the old.

**Comment by dsanchez31** [comment]
Ok. All work fine !

Thanks for your help. Very good stuf !

**Comment by akkie** [comment]
Nice to hear that!
