### ISSUE TITLE
Silhouette is not ExecutionContext transparent

### ISSUE THREAD

**Issue by joaoraf** [mohiva/play-silhouette#341]
Since there are several places where a Future is created and some callback methods that a user os Silhouette has to implement return a Future, an ExecutionContext is needed at those points.
Since it isn't been propagated from the library calls up to the user, the callback implementations must rely on a ExecutionContext which is not necessarily the same that the library uses, creating a possibly unnecessary thread switch to execute the callback.
I propose that the library should propagate an implicit ExecutionContext through its calls, allowing the callback methods to use if needed.

**Comment by akkie** [comment]
@see #342
