### ISSUE TITLE
Is it possible to store session customized

### ISSUE THREAD

**Issue by yuikns** [mohiva/play-silhouette#346]
I need to deploy several play servers, and I wish them share one jwt token system. Additionally, sometimes I need to restart the server to apply my update, it may cause users' token expired too quick.

Is it possible that I  store these tokens into redis/mongodb ?

Any help are appreciated.

**Comment by akkie** [comment]
You can configure the `JWTAuthenticatorService` to use a `AuthenticatorDAO` implementation. In this DAO you can then implement the logic to store the token in a backing store.
