### ISSUE TITLE
application.conf is out of date

### ISSUE THREAD

**Issue by aparamonov** [mohiva/play-silhouette#347]
Hi!

Is there reason to have file 'application.conf' in this library?
If so, I think we should remove 'application.secret' configuration property or at least rename it to 'play.crypto.secret'. This will fix warning in applications that use Play 2.4.0: [[33mwarn[0m] application in application-akka.actor.default-dispatcher-3 Req: - application.conf @ jar:file:/Users/aparamonov/.ivy2/cache/com.mohiva/play-silhouette_2.11/jars/play-silhouette_2.11-3.0.0-SNAPSHOT.jar!/application.conf: 5: application.secret is deprecated, use play.crypto.secret instead

Also, I see another one warning: [[33mwarn[0m] application in main Req: - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
So, we should get rid of logging configuration properties in the file too.

Thanks,
Alexey

**Comment by akkie** [comment]
Fixed with #349
