### ISSUE TITLE
DelegableAuthInfoService is missing in the latest codebase - master

### ISSUE THREAD

**Issue by santoshv98** [mohiva/play-silhouette#348]
I am creating a Play application that leverages play-Silhouette (latest based on play 2.4). I am using the current play-silhouette-seed as the base and I dont find DelegableAuthInfoService and AuthInfoService in play-silhouette. In addition save method has been pulled out of AuthInfoDAO 

I see all these were part of 2.0-RC2 but have been removed in the latest codebase. Any particular reason? Is this not required anymore?

Could you please help me understand what functionality these classes were bringing us ? What would we miss if our controllers don't use the AuthInfoService as part of their chain?

On another note, have these been refactored to AuthInfoRepository and DelegableAuthInfoRepository?  Could you please help me understand this?

**Comment by akkie** [comment]
Please see #326 and #334. The classes were renamed for the next 3.0 release and the seed template is currently out of date. I'll start today to update the seed template to the latest Play RC version.
