### ISSUE TITLE
LoginInfo explicit companion object.

### ISSUE THREAD

**Issue by optician** [mohiva/play-silhouette#363]
Utilization of explicit companion object removes `LoginInfo.tupled` method. This can be fixed with extending companion object from function `((String,String) => LoginInfo)`.
![alt scala console](https://leto20g.storage.yandex.net/rdisk/2dc66e5d42181838e3fc5bca87fb0bfe9c58d569b57c188a30d8b8c21af61e92/inf/YMcqqQ8-O33M8cYPtJhfLwFwDZcvxIjkTb_YbDw7JK4DxIJV5o7bHc6-6ktlY9WycX2nszOULNQlwEgqQnWyfg==?uid=0&filename=2015-05-30%2018-21-39%20C%20%20Windows%20system32%20cmd.exe.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=b9125343a562b6483dd72662f216ce30&force_default=no)

**Comment by akkie** [comment]
Could you create a pull request?

**Comment by akkie** [comment]
Fixed with #364

**Comment by studiodev** [comment]
Just for information, you can call the `tupled` method without extending the object by doing: `(LoginInfo.apply _).tupled`.

**Comment by optician** [comment]
Yep, I use this "hack", but it's easy to simplify.
