### ISSUE TITLE
why no a SessionStateProvider

### ISSUE THREAD

**Issue by gabadi** [mohiva/play-silhouette#369]
I've been working with this project for some time and is great

I've a question more than an issue in the project.

I've seen that the OAuth2StateProvider have 2 implementations: CookieStateProvider and DummyStateProvider

Why no a SessionStateProvider? is more secure with the cookie?

**Comment by akkie** [comment]
The problem with a session state is that we need a mechanism to invalidate the state, in the user session, after a certain time. A cookie has an expiry that we can set. So the cookie invalidates the state automatically at the moment it expires.

**Comment by gabadi** [comment]
In that case, i belive, that could be better to add the app secret or something like that to the

**Comment by akkie** [comment]
> In that case, i believe, that could be better to add the app secret or something like that to the encoding.
I mean, something that the hacker can not have access.

I'm not really sure I can follow you here? Do you have an issue with the CookieStateProvider?

> But i really don't know if i'm missing something, security is no my specialty.

You can read about the OAuth2 state param in the [RFC](http://tools.ietf.org/html/rfc6749#section-4.1.1). Here is also a description how the state should be used to protect an authorization request against [Cross-Site Request Forgery](http://tools.ietf.org/html/rfc6749#section-10.12).

**Comment by akkie** [comment]
I'll close this for now. Please reopen this issue if you have an issue with the CookieStateProvider.
