### ISSUE TITLE
Websocket 303 in Safari

### ISSUE THREAD

**Issue by hohl** [mohiva/play-silhouette#393]
I've implemented the Websockets like described in `Endpoints` section of the Silhouette docs, however when using it I always get "unexpected response code: 303" in Safari. In Chrome everything works fine. Any ideas what this can be caused by?

When I debug my application I see that when using Safari the app always jump into the left hand `Left(r)` line instead of `Right(MessageSocketActor.props(account) _)`.

*(Before I use SecureSocial and I didn't have any issue with Websockets.)*

*EDIT: I'm using the `CookieAuthenticator` if that's relevant.*

*EDIT2: Tried `SessionAuthenticator` too, but doesn't help.*

**Comment by akkie** [comment]
Mhh.., maybe Safari cannot handle the cookies for the Websocket!?

Does SecureSocial can handle Websockets?

**Comment by hohl** [comment]
Yes it does and auth worked fine there.

**Comment by akkie** [comment]
Could you please debug the request to see if the cookie is located in it?

**Comment by hohl** [comment]
Just verified it, it’s there.

**Comment by akkie** [comment]
It would be nice if you could find the root cause. I do not have a Safari to reproduce this issue.

I would set some breakpoints in the `retrieve` method of the authenticator to see if the authenticator could be extracted from cookie. Do you have enabled fingerprinting for the authenticator?

**Comment by hohl** [comment]
I'm happy if I can help you. However I spend a lot of time finding the issue myself, but I didn't yet - guess I've to less knowledge about what's going on in your library.

About `retrieve`: just debugged it, extraction works - the `Failure(error)` branch of the match statement is never visited.

**Comment by akkie** [comment]
Do you have set the logging level to debug? You have not answered my question regarding the fingerprinting. Where does it step out? On line [206](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala#L206), on line [207](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala#L207) or on line [209](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala#L209)?

**Comment by hohl** [comment]
Right now fingerprinting and SessionAuthenticator is used (since I hoped this would, however there is no change).

During the establishment of the websocket via Safari the following lines are written to the log:

    [info] c.m.p.s.i.a.SessionAuthenticatorService - [Silhouette][session-authenticator] Fingerprint Some(E418F2D4251E3F3DEC7C502F899B5DA0FCDFF498) doesn't match authenticator: SessionAuthenticator(LoginInfo(credentials,me@michaelhohl.net),2015-07-22T21:18:31.130+02:00,2015-08-21T19:12:38.536+02:00,Some(432000 seconds),Some(C626E55359030FB4CEB2D1D29455D9982CDEB703))
    [debug] a.c.ConnectionController - [Silhouette] Unauthenticated user trying to access '/api/connection/stream'
    [info] c.m.p.s.i.a.SessionAuthenticatorService - [Silhouette][session-authenticator] Fingerprint Some(E418F2D4251E3F3DEC7C502F899B5DA0FCDFF498) doesn't match authenticator: SessionAuthenticator(LoginInfo(credentials,me@michaelhohl.net),2015-07-22T21:18:31.130+02:00,2015-08-21T19:12:38.536+02:00,Some(432000 seconds),Some(C626E55359030FB4CEB2D1D29455D9982CDEB703))
    [debug] a.c.ChannelController - [Silhouette] Unauthenticated user trying to access '/api/channel/stream'

**Comment by akkie** [comment]
It seems that Safari sends different headers for Websocket and default HTTP requests and therefore the fingerprint doesn't match. So either you define a new `FingerprintGenerator` that can handle the difference or you disable fingerprinting. You should debug the headers currently implemented in the [DefaultFingerprintGenerator](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/util/DefaultFingerprintGenerator.scala#L47) to see which headers are different.

**Comment by hohl** [comment]
You are right they differ. Safari doesn't send ACCEPT_LANGUAGE and ACCEPT_CHARSET on websocket request.

**Comment by hohl** [comment]
And yes, disabling fingerprinting fixed my problem. Thank you for your help and for developing that great library. I previously used SecureSocial, but the project seemed to be dead and manually fixing bugs wasn't fun too, since code wasn't structured that well. I guess the transition to Silhouette was a good decision.

**Comment by akkie** [comment]
Nice to hear that!

**Comment by outsideMyBox** [comment]
Just for information I also had the issue for Microsoft Edge. I solved by creating a FingerprintGenerator that doesn't take into account ACCEPT_LANGUAGE and ACCEPT_CHARSET.
