### ISSUE TITLE
Provide Identity When Saving AuthInfo

### ISSUE THREAD

**Issue by bennythomps** [mohiva/play-silhouette#394]
A very common use case is to associate AuthInfo with a specific user. In some cases, it would be valuable to have the Identity available for additional context (i.e. "id") especially for denormalized storage.

**Comment by akkie** [comment]
Do you have a proposal how this could be changed? Replacing the `LoginInfo` with the `Identity` does not work, because an Identity can have more than one `LoginInfo` associated with it. And the `LoginInfo` -> `AuthInfo` association must be retained to select the specific `AuthInfo` for a provider. 

```
Identity -> LoginInfo -> PasswsordInfo
         -> LoginInfo -> OAuth1Info
         -> LoginInfo -> OAuth2Info    

```

I think if you really need the `Identity` in place then you could use the `LoginInfo` to query the `Identity` associated with it.

Do you have use a case for me? Maybe your problem could be solved in another way.

**Comment by bennythomps** [comment]
What I was hoping for is to have a primary user table with profile information structured like so (using Cassandra):
```
(id: UUID), first_name: String, last_name: String, email: String, logins: Map[String, String]
```

Then have an OAuth2 (and similar credential and OAuth1 tables) with a structure like so:
```
((user_id: UUID), provider_id: String, provider_key: String), access_token: String, expires_in: Int)
```

Like you mentioned I could just look up the user_id by `LoginInfo`, but I would prefer to avoid the overhead if possible.

I started last night on a PR, but it would just be a matter of including the Identity as a part of the AuthInfoDAO and up:

```scala
trait AuthInfoDAO[T <: AuthInfo, I <: Identity] {
```

**Comment by akkie** [comment]
If we add the identity to the DAO, then the overhead to fetch the Identity is only moved to other parts of Silhouette. The [CredentialsProvider](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala) as example, doesn't need the Identity to login a user. With your change it must fetch the `Identity` to update the credentials in the backing store.

I think also that it would violate the common DAO structure, where a DAO handles only one entity.

**Comment by bennythomps** [comment]
Maybe the larger issue is that the DAOs are enforced by the library which is somewhat uncommon. What is the benefit of including the DAOs? Isn't the importance more about consuming services at the library level and allow the application to access the data in a way that makes the most sense?

**Comment by akkie** [comment]
The DAOs are not enforced by the library, they are only one possible implementation. Silhouette has a very low coupling to the data access layer. The only points Silhouette touches the data access layer is through the `IdentityService.retrieve` or to the `AuthInfoRepository.find` and `AuthInfoRepository.update` methods.

>> Isn't the importance more about consuming services at the library level and allow the application to access the data in a way that makes the most sense?

In my opinion Silhouette is implemented in this way. If you have another idea how the library could be improved I'm open for your proposal.

**Comment by bennythomps** [comment]
I guess my suggestion would be to move the whole DelegableAuthInfoService/Repository to the seed project(s) or breaking it away from the real value add, the providers and authenticators, etc. I'll close this since I'll probably just avoid using DelegableAuthInfoService/Repository for my implementation.

**Comment by akkie** [comment]
Maybe we can create a `silhouette-extra` package

**Comment by bennythomps** [comment]
That would make sense to me
