### ISSUE TITLE
Logger conflict when extending Silhouette

### ISSUE THREAD

**Issue by studiodev** [mohiva/play-silhouette#395]
Hello,

Currently when you extends `Silhouette` in a controller, it inject the [Silhouette logger](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/Logger.scala#L26) into the controller, with the very common name: `logger`.

I think this object should be restricted to Silhouette classes, or at least have a less generic name. This would allow the user to use its own logger (it's a common practice to create a `Logger` trait with a `logger` inside, but the construction must be different than yours).

**Comment by akkie** [comment]
It seems that in [Play 3.0](https://groups.google.com/d/msg/play-framework/9Pf-xTUBt7c/-sHxvhPLFdQJ) all actions will be injected into controllers. So I think there is no need for a `Silhouette` trait in the next version of Silhouette anymore. In the meantime you could use a less generic name in your implementation. What do you think?

**Comment by akkie** [comment]
With Play 2.5 actions should be injected into controllers. I'll implement this in Silhouette 3.1.0. The old `Silhouette` controller will continue to work but it will be deprecated and removed in Silhouette 4.0.0.

Please see https://groups.google.com/forum/#!topic/play-framework-dev/xj247gQG6Hk

**Comment by akkie** [comment]
Fixed with #411
