### ISSUE TITLE
remember the link when login is prompted

### ISSUE THREAD

**Issue by hohl** [mohiva/play-silhouette#397]
When the user click a link anywhere and is not authenticated he gets redirected to the login page. However after logging in or signing up, the previous URL is forgotten and the user gets redirected to the default one. Any chance to remember the requested URL?

**Comment by akkie** [comment]
Hi,

this functionality doesn't pertain to the core of Silhouette. This should be implemented directly into your application.

Best regards,
Christian

**Comment by hohl** [comment]
I guess this may be done by storing the URL in a cookie before redirecting to `/login` (or whatever route someone is using). However this redirection is done `SecureAction` of Silhouette. May you give me an hint on how to catch that URL?

**Comment by akkie** [comment]
Silhouette doesn't know what type of result should be returned if a user tries to access a secured action. Instead it calls either the [local](http://silhouette.mohiva.com/docs/endpoints#section-local-fallback) or [global](http://silhouette.mohiva.com/docs/endpoints#section-global-fallback) fallback methods. Only if these methods are not defined then it returns a [default response](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/util/DefaultEndpointHandler.scala#L24). So in your case you should define a global or local fallback method. If you use the Seed Template then you have already a [global fallback](https://github.com/mohiva/play-silhouette-seed/blob/master/app/utils/ErrorHandler.scala#L37) method defined.

**Comment by hohl** [comment]
Ah, got it. Thank you!

**Comment by akkie** [comment]
You're welcome!

**Comment by epot** [comment]
Any chance to get an up-to-date link explaining how to do that with the latest version?
