### ISSUE TITLE
UnexpectedProviderError: State cookie doesn't exists for name

### ISSUE THREAD

**Issue by nelsonblaha** [mohiva/play-silhouette#398]
```
controllers.SocialAuthController - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.OAuth2StateException: [Silhouette][CookieState] State cookie doesn't exists for name: OAuth2State
```
I get this when Google auth callback attempts the authenticate() in SocialAuthController.authenticate. I changed the method to a UserAwareAction.async to allow the user to add additional auths while logged in. This worked ok in Silhouette 2.0... is there something about 3.0 that keeps me from being UserAware if the cookie isn't set yet?

**Comment by akkie** [comment]
Please can you post your config for the state provider?

**Comment by nelsonblaha** [comment]
Fixed somehow by copying configuration from a different project.
