### ISSUE TITLE
A normal form post causes silhouette to show unauthorized, so it does not work

### ISSUE THREAD

**Issue by PhilAndrew** [mohiva/play-silhouette#399]
For the form I added here:

https://github.com/PhilAndrew/silhouette-is-form-bug/blob/bcbe51d56938d35dc12b898d966ab65043de6065/app/views/home.scala.html

When I select the drop down, the form should submit.

But the page says "Unauthorized
You must be authenticated to access this page."

What is wrong here? Other files are:

https://github.com/PhilAndrew/silhouette-is-form-bug/commit/bcbe51d56938d35dc12b898d966ab65043de6065

https://github.com/PhilAndrew/silhouette-is-form-bug/blob/master/public/script/main.js

https://github.com/PhilAndrew/silhouette-is-form-bug/commit/06bb16ba87eb19b0b2c2912ce2f196eb7648346a

Anyway just use the latest of that git repo and you can see the bug when you select the dropdown.

**Comment by akkie** [comment]
Hi,

The seed template uses the `CSRFFilter` by default. Therefore you must implement a CSRF token into your form.

https://www.playframework.com/documentation/2.4.x/ScalaCsrf
```
@form(routes.ItemsController.save()) {
    @CSRF.formField
    ...
}
```

Anyway, this has nothing to do with the Silhouette library itself. The next time you have an issue with the seed template, please open the issue directly there. So other users with the same problem can find the issue.

**Comment by PhilAndrew** [comment]
Thanks! I don't even know what CSRF is yet.
