### ISSUE TITLE
PBKDF2 support in PasswordHasher

### ISSUE THREAD

**Issue by Rushit** [mohiva/play-silhouette#402]
Hi,

I was wondering what it will take to add PBKDF2 support for password. Main difference vs BCrypt is that it will require to store iteration column in DB. Although, I am beginner in play and slick ecosystem but ready to work on PR.

**Comment by Rushit** [comment]
PR to start discussion is at - https://github.com/mohiva/play-silhouette/pull/403

**Comment by akkie** [comment]
Closed this because pull request exists.
