### ISSUE TITLE
BasicAuth does not support passwords with ":" symbol

### ISSUE THREAD

**Issue by mavarazy** [mohiva/play-silhouette#404]
With current implementation BasicAuthentication does not support ":" field in request
BasicAuthentication:100 Base64.decode(header.replace("Basic ", "")).split(":") 
Need to be changed

**Comment by akkie** [comment]
I'm not sure I can follow you? Please could you provide a more detailed example and description?

**Comment by akkie** [comment]
I think I know what you mean. If you use a colon in the password then it doesn't work because the string gets split by the colon into an array. And then the last part of the password after the colon gets stripped.

Definitely a bug!
