### ISSUE TITLE
Github login does not pick up user email

### ISSUE THREAD

**Issue by rorygraves** [mohiva/play-silhouette#415]
When using Github for authentication (and scope user:email), the provider doe not pick up the email address.
The issue appears to be that the email is assumed to be part of the main response

https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProvider.scala#L99

But in fact (based on https://developer.github.com/v3/users/emails/ ) you have to use a second endpoint (with your token) to access the available email addresses.

Should acquiring the email address be put into the main workflow, or should I add a secondary step on the application side to update the email information?

Thanks 

Rory

**Comment by akkie** [comment]
Hi,

The main email address is contained in the [user response](https://developer.github.com/v3/users/#get-a-single-user) and this is what Silhouette uses. Does this not work for you?

Cheers,
Christian

**Comment by rorygraves** [comment]
It's not picking up the email address for me. Online search suggested the email is not in the main GitHub response. I will investigate further and report back. 

Thanks. 

Rory

**Comment by rorygraves** [comment]
Ah, I see, my email address is not public on my profile.
I believe the user:email scope means that it is visible on the specific api, but not returned as part of the main response.

Thanks

Rory
