### ISSUE TITLE
Permissions and Roles

### ISSUE THREAD

**Issue by ntenisOT** [mohiva/play-silhouette#420]
Hello I would like to ask if I am able to have permission based authentication instead of only role based. 

For example I would like to annotate each controller with a permission and then assign that permission to a specific role.

For example:

Permission ->               Role
==========                ====
"admin.createUser" -> admin
"admin.createUser" -> moderator

Deadbolt support this with Permissions:

    // subject must have a permission with the exact value "admin.printer" 
    def permittedFunctionA = deadbolt.Pattern("admin.printer", PatternType.EQUALITY) {
        Action {
            Ok(accessOk())
        }
    }

**Comment by akkie** [comment]
@see https://groups.google.com/forum/#!topic/play-silhouette/0ZNF0lJFvUY
