### ISSUE TITLE
LinkedInProvider restricts the fields returned to those present in the CommonSocialProfile

### ISSUE THREAD

**Issue by meghana-viswanath** [mohiva/play-silhouette#421]
Hi,

Is there a reason for restricting the fields in the LinkedIn provider to the ones in CommonSocialProfile - https://api.linkedin.com/v1/people/~:(id,first-name,last-name,formatted-name,picture-url,email-address,positions)?format=json&oauth2_access_token=%s"

Is there a way to override this? I have currently implemented a custom provider for this since I needed to pull in more profile info.

Thanks.

**Comment by akkie** [comment]
Hi,

this are the information the default provider can handle. I'm not sure what you try to do? But if you try to fetch more information then you must either override the provider or use a custom profile parser. But in both cases you must implement custom code for custom fields. So I'm not sure if it solves an issue if we remove the restriction for the fields. Maybe you can specify your issue a bit more.

Cheers,
Christian

**Comment by meghana-viswanath** [comment]
Hi Christian,

Overriding just the profile parser will not work here since the fields are restricted in the LinkedIn URL itself. Which means that even if the app has been granted permissions to look at all profile info, it only returns the ones specified. 
And the only way to override this is to create a custom provider and change the URL constant value to -https://api.linkedin.com/v1/people?format=json&oauth2_access_token=%s" (without specifying the fields, so all of the profile info is returned.)

So I was thinking that if the URL constant in the LinkedIn provider was as specified above, then developers would only require to override the profile parser and not the provider also.

Thanks,
Meghana.

**Comment by akkie** [comment]
Hi Meghana,

If we do not restrict the fields then the complete profile is returned on every API call. This could lead to slower API calls because of the additional traffic. Instead we could allow to override the API URL in the config. What do you think?

Cheers,
Christian

**Comment by meghana-viswanath** [comment]
Sure. I think that is a good idea. It means devs can specify exactly what they want returned *and* also not have to implement a custom provider unnecessarily.

**Comment by akkie** [comment]
Fixed with #434
