### ISSUE TITLE
How to hold reference to websocket / send messages?

### ISSUE THREAD

**Issue by i-schuetz** [mohiva/play-silhouette#428]
Hi,

I'm following the documentation to create a websocket with 3.0.0:

```scala
def socket = WebSocket.tryAcceptWithActor[String, String] { request =>
  implicit val req = Request(request, AnyContentAsEmpty)
  SecuredRequestHandler { securedRequest =>
    Future.successful(HandlerResult(Ok, Some(securedRequest.identity)))
  }.map {
    case HandlerResult(r, Some(user)) => Right(MyWebSocketActor.props(user) _)
    case HandlerResult(r, None) => Left(r)
  }
}
```

But I cannot find, how can I store a reference to the created sockets such that the server can send them arbitrary messages? `tryAcceptWithActor` accepts a function that creates `Props` and I don't know exactly how to hook in in that. There's also a synchronous version `acceptWithActor` where I think I can get the actor but I'd prefer to use the asynchronous one. Maybe I'm missing something obvious, this is new land to me.

**Comment by akkie** [comment]
This isn't really an issue. Please could you use the mailing-list or the chat to ask questions.
