### ISSUE TITLE
Best way to integrate user's ID in JWT "sub" field

### ISSUE THREAD

**Issue by mplatt** [mohiva/play-silhouette#430]
This is a question—not a bug—I hope this is a good place to raise this. If not, please feel free to close this issue.

I am using play-silhouette to issue JSON Web Tokens for REST API communication. I my use case one user can hold authentication information of multiple providers. Currently I use a custom claim field to store the user ID. This feels wrong to me though as in my opinion the user is the subject of the token and should be part of the sub field (along with the other LoginInfo).
For this reason, I would like to add the user's ID to the sub field of my JWT. I didn't find a clean way to do this (other than extending ```JWTAuthenticator``` and ```LoginInfo``` and perhaps a bunch of other classes) and was wondering if someone could suggest a better way to achieve this.

**Comment by akkie** [comment]
Sorry but this is the wrong place for questions. The [Readme](https://github.com/mohiva/play-silhouette/blob/master/README.md) and the [contribution guidlines](https://github.com/mohiva/play-silhouette/blob/master/CONTRIBUTING.md) points you to the right place.
