### ISSUE TITLE
Overriding the configured redirectURL for an OAuth2 provider when calling `getAccessToken`

### ISSUE THREAD

**Issue by theshortcut** [mohiva/play-silhouette#431]
I'm building a central authentication server which may have a number of login urls across subdomains. Satellizer, for example, now sends a `redirectUri` parameter along with the `code` key in the post body. It'd be nice to be able to use that in place of the configured provider `redirectURL` since otherwise validation will fail. Please let me know if I'm overlooking an existing way to deal with the issue of handling more than a single redirect URL.

**Comment by akkie** [comment]
You are able to override the settings for every provider with the [withSettings](http://silhouette.mohiva.com/docs/config-oauth2-based-providers#override-the-configuration-locally) method on every provider. 

But note: There is currently a [bug](https://gitter.im/mohiva/play-silhouette) in this implementation. Please look at the comment from @felipefzdz

**Comment by akkie** [comment]
Fixed with https://github.com/mohiva/play-silhouette/pull/433
