### ISSUE TITLE
Google avatar size

### ISSUE THREAD

**Issue by chrissom** [mohiva/play-silhouette#443]
When I authenticate a user against Google, I get always an avatar with a size of 50px: ```https://lh3.googleusercontent.com/[GOOGLE-ID-UGLY-STRING]/photo.jpg?sz=50```.

Is there an easy way to change the default size?

**Comment by akkie** [comment]
This is the default Google returns. But this parameter is variable. If you change 50 to 100 then you get a 100px image. I'm not aware of an option for the Google API to return a URL with a higher value. Why should they? With a string replace you can change the URL before you store it or at the point you render your template.

PS: Please do not use the issue tracker for questions! There is a big teaser in the [README](https://github.com/mohiva/play-silhouette#support) which shows you the correct place to ask questions.
