### ISSUE TITLE
silhuete.xxxAction not executed

### ISSUE THREAD

**Issue by dejvid** [mohiva/play-silhouette#460]
Hi,

I have moved project from Silhuette 3.0 to 4.0.0.BETA4. I have configured silhuete with persistance, not memory and Im useing mongo for persistance. Everything compiles and runs ok except this action
```
class SilTest @Inject()(silhouette: Silhouette[SubscribedAdminEnv]) extends  Controller {

  def simpleAction = {
    Logger.logger.info("SilTest->simpleAction UnsecuredAction before ")
    val act = silhouette.UnsecuredAction( {
      Logger.logger.info("This is never fired")
      Ok("OK")
    })
    Logger.logger.info("SilTest->simpleAction UnsecuredAction after ")
    act
  }

}

````
If invoking this action from brosser this prints to console
```
[info] application - SilTest->simpleAction UnsecuredAction before 
[info] application - SilTest->simpleAction UnsecuredAction after 
```
And request is never finished(no error on browser side just forever loading). I ve set breakpoint in line Ok of above example and it is not executed. And it is never executed no matter what silhouette.xxxxAction I am useing. But example play-silhuette-seed work perfectly. 

What are possible reasons for this?

**Comment by akkie** [comment]
This isn't the place to answer questions. Please read this carefully.

https://github.com/mohiva/play-silhouette/blob/master/README.md#support
