### ISSUE TITLE
SecuredRequest[E, B] not compatible with Play2.5.x ActionFilter

### ISSUE THREAD

**Issue by gguan** [mohiva/play-silhouette#462]
ActionFilter requires a `protected def filter[A](request: R[A]): Future[Option[Result]]` implementation, while the new SecuredRequest[E, B] class doesn't conform request: R[A].

**Comment by akkie** [comment]
This isn't an issue. Please look at the type signature of the `ActionBuilder` which a Silhouette Action depends on and a `ActionFilter`.

```scala
trait ActionBuilder[+R[_]] extends ActionFunction[Request, R]
```

```scala
trait ActionFilter[R[_]] extends ActionRefiner[R, R]
```

Both share the same base trait `ActionFunction`, so they all compatible together.

You must use a bit voodoo here called [higher kinded types](http://blogs.atlassian.com/2013/09/scala-types-of-a-higher-kind/). You can see how it's implemented in  Silhouette if you look at the [SecuredRequestHandlerBuilder](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/actions/SecuredAction.scala#L56).

```scala
RequestHandlerBuilder[E, ({ type R[B] = SecuredRequest[E, B] })#R]
```
