### ISSUE TITLE
Parsing happens before authentication

### ISSUE THREAD

**Issue by muuki88** [mohiva/play-silhouette#465]
Hi,

We have a problem, when using the `SecuredAction` together with body parsers. Play tries to parse the body first and returns with validation errors, even thought the endpoint is only available with authentication. Our expected behaviour would be to authorization first and the validate the body.

The code looks like this

```scala
// ApiEnv.scala
import com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticator
import com.mohiva.play.silhouette.api.Env
import model.UserIdentity
trait ApiEnv extends Env {
  type I = UserIdentity
  type A = JWTAuthenticator
}

// MyController.scala
import com.mohiva.play.silhouette.api.Silhouette
import auth.ApiEnv

class MyController @Inject() (
    silhouette: Silhouette[ApiEnv]
) extends Controller {

  def postSecured() = silhouette.SecuredAction.async(parse.json[MyModel]) { request =>
    val model = request.body
    // do something with the model
    Created
  }
}
```

As `SecuredAction` is an `ActionBuilder` [composition as described in the play docs](https://www.playframework.com/documentation/2.5.x/ScalaActionsComposition#composing-actions) doesn't work.

Ideally silouhette would do things in the "correct" (?) order, but AFAIK this is more a thing in play. 
So the second option would be to have an `Action` available along with the Builder, so you can call the code like

```scala
  def postSecured() = silhouette.Secured { securedRequest =>
      Action(parse.json[MyModel]) { request => 
         val identity = securedRequest.identity
         val model = request.body
        // do something with the model
        Created
     }
  }
}
```

However I'm not very sure if this works out, because it seems play delegates the parsing to the outside.

We are using version `4.0.0-BETA4` of silouhette and play `2.5.1`.

**Comment by viennv1709** [comment]
I don't think authentication should be happened before parsing the body of the request.  Why do you want this flow.

**Comment by muuki88** [comment]
From my point of view, a user shouldn't have any other return type that `Unauthorized` if he's not allowed to use this endpoint. I don't want any information to leak out of endpoints, if the requesting user isn't allowed to use it.

**Comment by viennv1709** [comment]
In fact, I don't want to see this error in my console for `Unauthorized` action either.

![error](https://cloud.githubusercontent.com/assets/5088270/14403640/ff021632-fe89-11e5-9037-d95fad1828aa.PNG)

**Comment by akkie** [comment]
> Play tries to parse the body first and returns with validation errors, even thought the endpoint is only available with authentication. 

This is how Play handles the incoming request. In Play a request consists of the header data and a body. There are two traits to handle this. The `RequestHeader` which defines all the header data and derived trait `Request[B]` with the body part. The raw type `B` in the `Request` class describes the body. So without the body the [Request](https://github.com/playframework/playframework/blob/9bf7399f1e2b53ba4a3c3405acd1b74fe96b53e6/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L318) cannot be instantiated. And without a request, Silhouette cannot read data from request(headers as also body params) which are necessary for the authentication process.

> As SecuredAction is an ActionBuilder composition as described in the play docs doesn't work.

Why does composition not work?

> Ideally silouhette would do things in the "correct" (?) order, but AFAIK this is more a thing in play. 
So the second option would be to have an Action available along with the Builder, so you can call the code like

Why do you not write something like this?

```scala
def postSecured() = silhouette.SecuredAction.async(parse.json) { request =>
  request.body.validate[MyModel].map { model =>
    // do something with the model
    Created
  }.recoverTotal { e => Future.successful(BadRequest("Json invalid")) }
}
```

Sure, in this case you would also get a `415 Unsupported Media Type` error if you do not send a Json request. But I think this is OK.

**Comment by muuki88** [comment]
@akkie thanks for your detailed response. We will probably  go with your suggestion. The `async(parse.json[MyModel])`
