### ISSUE TITLE
GitHub does not provide private email with user

### ISSUE THREAD

**Issue by ThmX** [mohiva/play-silhouette#475]
I also have an issue related to #415. Would it be a good idea to add some kind of fallback action in order to use https://developer.github.com/v3/users/emails/ and directly filter the primary and verified email before creating the profile?

I implemented a duplicated version of the `GitHubProvider` in order to retrieve the email if it was not provided by default. But I don't like having it directly inside my duplicate of `BaseGitHubProvider.buildProfile`, I would propose to add a step following `SocialProvider.buildProfile` that can be overridden in order to execute other actions on that provider.

**Comment by akkie** [comment]
Normally, we have the [profile builder and parser](http://silhouette.mohiva.com/v4.0/docs/providers#social-profile-builders-and-parsers) for such a case. I'm not sure if it makes sense to implement duplicate functionality.

**Comment by ThmX** [comment]
I entirely agree with that, except that in the case of Github, we need to make 2 API calls.
And with profile builder and parser, it needs to be only one call, or is there something I missed? (Especially that the parser of GitHubProvider needs only a JsValue)

**Comment by akkie** [comment]
No, you can make as many API calls as you need. You can use the main functionality of the GitHub provider and extend it with your custom functionality.

**Comment by ThmX** [comment]
Would it be useful/interesting having it part of the code as an extended GithubProvider?

**Comment by akkie** [comment]
No, I would not do that, because then there where a GitHub provider with this functionality and then another user want this functionality and so forth. We provide the base functionality and the tools so that the user can easily extend it.
