### ISSUE TITLE
UserAwareAction.async

### ISSUE THREAD

**Issue by mslinn** [mohiva/play-silhouette#490]
This is what the docs suggest, which is verbose:

```
class Application(silhouette: Silhouette[DefaultEnv]) extends Controller {
  def unsecuredRequestHandler = Action.async { implicit request =>
      silhouette.UnsecuredRequestHandler { _ =>
        Future.successful(HandlerResult(Ok, Some("some data")))
      }.map {
        case HandlerResult(r, Some(data)) => Ok(data)
        case HandlerResult(r, None) => Forbidden
      }
    }
  }
```

This next incantation is not mentioned in the Silhouette docs, and it compiles, but it returns `You must be authenticated to access this page.` Is there any reason this should not work, or have I found a bug? 

    class Application(silhouette: Silhouette[DefaultEnv]) extends Controller {
      def unsecuredRequestHandler = silhouette.UserAwareAction.async { request =>
          Future.successful(HandlerResult(Ok, Some("some data")))
        }.map {
          case HandlerResult(r, Some(data)) => Ok(data)
          case HandlerResult(r, None) => Forbidden
        }
      }
    }

**Comment by akkie** [comment]
I'm not sure what you try to achieve? Do you need a RequestHandler or an Action? This are two different things. And I think the docs are really clear here.

**Comment by mslinn** [comment]
I'm confused, and on several levels. I've used SecureSocial for years (and was a contributor), and Silhouette is similar enough to SS that I may be making incorrect assumptions. You know that I've read through the docs carefully, because you accepted my edits.

In the remainder of this reply, please understand that I am grateful for your work, and am sharing my experience trying to use it. I do not mean to sound critical. I have attempted to state the facts as I have found them without sounding critical, but I fear I may not have been entirely successful in this regard.

Because markdown has limited formatting capability, each of my points is separated by a horizontal line instead of numbers or bullets.

Onwards!

--

The only place that the docs discuss `RequestHandler` and `Action` is the [Endpoints page](http://silhouette.mohiva.com/docs/endpoints), and the only place I could find that the two concepts are related is this single phrase: "Silhouette provides a replacement for Play’s built in `Action` class named `SecuredAction` which is based on the `SecuredRequestHandler`." Seems like `SecuredAction` is a subclass of `SecuredRequestHandler`. 

I do not understand how these concepts differ, except that one apparently builds on the other. Do I need a `RequestHandler` or an `Action`? No idea. How can I make that determination?

--

`play-silhouette-seed`'s `SignInController` contains this code, which I am puzzling over:
````
def submit = silhouette.UnsecuredAction.async { implicit request => ... }
````
With SS, I would have used a `UserAwareAction`, and the body of the closure would be executed whether or not the user authenticated successfully. Seems that is not how Silhouette works: the body is not executed if a user does not authenticate. Also, the construct `silhouette.UnsecuredAction.async` is not mentioned in the Silhouette docs.

--

I am unclear on how to examine the authentication process using a debugger. Where might I place breakpoints to watch the user authentication process?

--

The code comments are not helpful; trite comments such as the following do not provide value, and might as well not be there:
```
/**
   * The instance of the unsecured request handler.
   */
  val requestHandler: UnsecuredRequestHandler
```

It would be more helpful if the comment explained what the purpose of the variable is, any expectations of the values it might assume, how might be used, and @See references to where its purpose and usage is explained. 
 
Another example of a pointless comment:

```
/**
 * Default implementation of the [[UnsecuredRequestHandler]].
 *
 * @param errorHandler The instance of the unsecured error handler.
 */
class DefaultUnsecuredRequestHandler @Inject() (val errorHandler: UnsecuredErrorHandler)
```

If this comment was not present any reader with a modicum of understanding of Scala would have immediately known the information provided in the comment. Information that might be useful would include behavioral characteristics of `DefaultUnsecuredRequestHandler`, when to override this class, and how to debug it. To my earlier point, and as an example of behavioral characteristics, is the body of the `UnsecuredRequestHandler` executed if a user does not authenticate?

--

My immediate purpose is to complete the integration of the code provided by `play-silhouette-seed` into the Play project I have been working on. Once I understand how Silhouette works I'll contribute back.

**Comment by akkie** [comment]
Mike, constructive criticism is always good and I really appreciate your criticism!

---

> I do not understand how these concepts differ, except that one apparently builds on the other. Do I need a RequestHandler or an Action? No idea. How can I make that determination?

You need a `SecuredAction`, `UserAwareAction` or `UnsecuredAction` if you like to replace Play's `Action`. The `RequestHandler` implementations can be used mainly for WebSockets. But there are also use-cases which needs the concept of the `RequestHandlers` inside default Play actions. With this concept the action is always processed, but you can use the security parts from Silhouette inside of these action.

In Play you do not have only `Actions` to handle incoming requests. An application can also intercept requests in a `Filter` implementation or it can handle WebSockets. Therefore the documentation page is named `Endpoints` and not `Actions`. For all this kind of endpoints the functionality is encapsulated in the `RequestHandler` implementations.

The documentation is structured in the following way. Please let me know how we can improve the documentation so that it's more clear.

**RequestHandlers**

We explain the request handlers first because all other implementations are based on them. I think the functionality of all the tree implementations is explained in detail.
 
> There exists a SecuredRequestHandler which intercepts requests and checks if there is an authenticated user. If there is one, the execution continues and the enclosed code is invoked.

> The UnsecuredRequestHandler does the opposite of the SecuredRequestHandler. It intercepts requests and checks if there is a not-authenticated user. If there is one, the execution continues and the enclosed code is invoked.

> There is also a UserAwareRequestHandler that can be used for endpoints that need to know if there is a current user but can be executed even if there isn't one.

There exists examples for all tree implementations which shows how actions can be implemented with request handlers.

**Actions**

Here we explain that every action type is based on a specific request handler type. We do not explain the functionality again because the functionality is already explained in the `RequestHandlers` section.

There exists examples for all tree implementations.

**WebSockets**

Here we explain that WebSockets can be handled with the request handler implementations.

---

> With SS, I would have used a UserAwareAction, and the body of the closure would be executed whether or not the user authenticated successfully. Seems that is not how Silhouette works: the body is not executed if a user does not authenticate. Also, the construct silhouette.UnsecuredAction.async is not mentioned in the Silhouette docs.

The `UnsecuredAction` is explained in the docs. If you read the `Actions` section then you find the `UnsecuredAction`. It states that is implemented on top of the `UnsecuredRequestHandler` and if you look at the functionality of the `UnsecuredRequestHandler` then it is explained how it works.

> The UnsecuredRequestHandler does the opposite of the SecuredRequestHandler. It intercepts requests and checks if there is a not-authenticated user. If there is one, the execution continues and the enclosed code is invoked.

---

> The code comments are not helpful ...

Yes, that could be improved!

> Another example of a pointless comment: Default implementation of the [[UnsecuredRequestHandler]].

In my opinion the comment is completely correct. It points out that it is the default implementation of the `UnsecuredRequestHandler`. And if you look at the `UnsecuredRequestHandler` trait, then the doc comment explains the functionality. I'm not sure if it makes sense to explain the functionality again.

Please see http://api.silhouette.mohiva.com/4.0.0/#com.mohiva.play.silhouette.api.actions.DefaultUnsecuredRequestHandler

**Comment by mslinn** [comment]
I think the docs need a top-down explanation - and you have made a good start right here in this conversation. There would be immediate benefit to users if large portions of your answer were incorporated into a new [Basic page](http://silhouette.mohiva.com/docs), called **Overview**, right after the **Features** page.

You know the code base so well that it is likely difficult to explain how to work with Silhouette from the beginning. I would like to suggest that the code provided in the sample app `play-silhouette-seed` project be the inspiration for the documentation provided at http://silhouette.mohiva.com/doc. In particular, the idioms that appear in the  `play-silhouette-seed` project should be discussed in the official docs. Once again I must mention that this construct, which appears throughout `play-silhouette-seed`, needs special explanation:

    silhouette.UnsecuredAction.async { implicit request ... }

A more general form of my question was asked in issue #385 (The documentation lacks a "getting started" part). Your response was, in part:

- Include the library (_easy_)
- Choose the appropriate authenticator (_I still cannot figure out how to enable/disable authenticators; I only understand how to configure them_)
- Create your identity (_What does this mean?_)
- Create controllers based on the needed auth mechanism (_currently under discussion_)
- Write the services and models (_play-silhouette-seed demonstrates this very well_)
- Wire dependencies (_easy_)

Getting back to my immediate problem, when a user attempts to log into in my app I see a call to the `SignInController`'s `UnsecuredActionBuilder` constructor but there is never a call to `UnsecuredActionBuilder.invokeBlock`; so something is different between my app and `play-silhouette-seed`. Perhaps I need to configure something? I find it difficult to follow the logic. What should the general sequence of events / control flow be for user login? What should I look for in order to determine why `UnsecuredActionBuilder.invokeBlock` is never called?

**Comment by mslinn** [comment]
I do not need to support multiple forms of authentication, and I want users to be able to log in with their userID & password instead of email address & password. 

I wonder if perhaps the problem I am facing relates to the `DelegableAuthInfoDAO` implementation I am using. I did not change it from `InMemoryAuthInfoDAO` used in `play-silhouette-seed`; in that project it merely consists of a `Map[[LoginInfo, T]`, where `T` is always `com.mohiva.play.silhouette.api.util.PasswordInfo` (for my project). 

The most important method in `InMemoryAuthInfoDAO` for user signin is `find`, which returns an instance of `Future[Option[T]]`, which is for my project is always `Future[Option[PasswordInfo]]`:
```
class InMemoryAuthInfoDAO[T <: AuthInfo: ClassTag] extends DelegableAuthInfoDAO[T] {
  def find(loginInfo: LoginInfo): Future[Option[T]] = {
    Future.successful(data.get(loginInfo))
  }
}
```
Thus we see that `InMemoryAuthInfoDAO.find` must be able to retrieve or construct an instance of `PasswordInfo` if the user's `loginInfo` is found.

Silhouette defines `PasswordInfo` as:

```
case class PasswordInfo(
  hasher: String,
  password: String,
  salt: Option[String] = None
) extends AuthInfo
```

My user table currently stores the hashed password, email address and user id. Somehow I need to be able to use this information to create an instance of `PasswordInfo`; however I don't know if it is possible or advisable to be able to create an instance of `PasswordInfo` from a user's hashed password. Some advice would be appreciated. It does not feel right to create a database table to store `PasswordInfo` for each user, so there needs to be a way to create an instance of `PasswordInfo` for each user on demand. My best guess is that I need to write something like:

```
class DBAuthInfoDAO[T <: AuthInfo: ClassTag] extends DelegableAuthInfoDAO[T] {
  def find(loginInfo: LoginInfo): Future[Option[T]] = Future.successful {
    Users.findByEmail(loginInfo.providerKey).map { user =>
      val passwordInfo: PasswordInfo = ???
      passwordInfo
    }.getOrElse(None)
  }
```

**Comment by akkie** [comment]
Mike, I'm not sure this is the right place to discuss such things. We should move over to the mailing list. Maybe you could create different threads for your question because this issue gets really confusing. For suggestions related to the getting started guide, you can use the already existing issue(#385).

**Comment by mslinn** [comment]
Why don't we instead split this thread into a docs-related page, where we collaborate on new and improved docs (much of what has been written would be generally useful in different areas of the docs), and I'll ask my question on the ML. Does readme.io have a draft capability where multiple authors can collaborate? 

In the meantime, work on my project has halted because I am stuck on the last question I asked.

**Comment by akkie** [comment]
We could create a Google Doc Document for the collaboration.

I've also some problems to understand your last question. I'm not really sure what problem you are facing. Have you seen this [method](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala#L89)? Maybe that solves your issue.

**Comment by mslinn** [comment]
I had not noticed `CredentialsProvider.loginInfo` before. Thank you for pointing it out. Judging by the (helpful!) code comments, this may be exactly what I need. I will try it.

We've already captured some good information for the docs, and it is already in markdown format. Google Docs would require translating from markdown to html, and then back again :( I wonder if we could share gists, or make a shared github/bitbucket/gitlab project for collaborating on docs before porting them to readme.io

**Comment by mslinn** [comment]
Unfortunately `CredentialsProvider.loginInfo` does not seem to do what I need.

I [posted to the mailing list](http://silhouette.mohiva.com/v4.0/discuss/57addb243215100e00bcf3f7), but the columns are so narrow as to make the code hard to read. I also dislike the inability to preview the posting. I am reposting here. Questions are embedded in the code.

```
/** An implementation of the DelegableAuthInfoDAO that computes AuthInfo instead of storing it.
  * For this webapp, Credentials are always constructed from userId and password: `Credentials(userId, password)`
 * @tparam T For this webapp, T is always PasswordInfo. */
class DBAuthInfoDAO[T <: AuthInfo: ClassTag] @Inject() (
  credentialsProvider: CredentialsProvider,
  executionContext: ExecutionContext
) extends DelegableAuthInfoDAO[T] {

  /** Computes PasswordInfo from the given loginInfo.
   * @return `Future[Option[PasswordInfo]]` or None if no user exists for the given loginInfo. */
  def find(loginInfo: LoginInfo): Future[Option[T]] = Future.successful {
    val submittedUserId = loginInfo.providerKey
    Users.findByUserId(submittedUserId).map { user =>
      // How to construct a PasswordInfo instance here?
    }
    None // just so this compiles
  }

  // TODO when and why is this called?
  def add(loginInfo: LoginInfo, authInfo: T): Future[T] = {
    // data += (loginInfo -> authInfo)
    Future.successful(authInfo)
  }

  // TODO when and why is this called?
  def update(loginInfo: LoginInfo, authInfo: T): Future[T] = {
    // data += (loginInfo -> authInfo)
    Future.successful(authInfo)
  }

  // TODO when and why is this called?
  def save(loginInfo: LoginInfo, authInfo: T): Future[T] = {
    find(loginInfo).flatMap {
      case Some(_) => update(loginInfo, authInfo)
      case None    => add(loginInfo, authInfo)
    }
  }

  // TODO when and why is this called?
  def remove(loginInfo: LoginInfo): Future[Unit] = {
    // data -= loginInfo
    Future.successful(())
  }
}
```

**Comment by akkie** [comment]
Please let us discuss this in the [chat](https://gitter.im/mohiva/play-silhouette) or the [mailing list](https://groups.google.com/forum/#!forum/play-silhouette).
