### ISSUE TITLE
Logging into multiple Github Applications from a single Play application

### ISSUE THREAD

**Issue by Saheb** [mohiva/play-silhouette#499]
Usecase is to configure clientIds/Secrets for two OAuth Github applications, configuring them and signing into them from a Single Play application. Like a user access vs admin access authorization.

**Comment by akkie** [comment]
### Are you looking for help?

This is an issue tracker, used to manage and track the development of Silhouette. It is not a support system and so it is not a place to ask questions or get help. If you're not sure if you have found a bug, the best place to start is with either the [forum](http://discourse.silhouette.rocks/) or [Gitter channel](https://gitter.im/mohiva/play-silhouette). If you have a feature request, the [forum](http://discourse.silhouette.rocks/) is better than an issue tracker to discuss it.
