### ISSUE TITLE
Build for Play 2.6.0-M1 / Scala 2.12

### ISSUE THREAD

**Issue by mslinn** [mohiva/play-silhouette#506]
The changes I have encoutered for Play 2.6.0-M1 have been easy to deal with.

**Comment by liao0007** [comment]
@mslinn is there a quick fix for 2.6.0-M1 for now?

**Comment by Jacke** [comment]
:+1:

**Comment by akkie** [comment]
Please see #509 for the progress

**Comment by akkie** [comment]
Fixed with #509
