### ISSUE TITLE
Use sbt 0.13.13 g8 generator

### ISSUE THREAD

**Issue by charafau** [mohiva/play-silhouette#507]
Hello, I asked on gitter's room but no reply.

Since sbt 0.13.13 and play examples with generators, maybe it would be better to create some g8 generators and make it easier to apply silhouette into new project, with sql migrations, forms and everything? Reference links:

```
https://playframework.com/download#starters
would be nice just to write g8Scaffold silhouette and generate migrations, user class and form
```

**Comment by akkie** [comment]
The core of Silhouette itself cannot be used as template. We could provide templates for the seed templates. Please open an issue there.
