### ISSUE TITLE
Play Silhouette Persistence Memory has version 4.0.0-BETA4

### ISSUE THREAD

**Issue by mkokho** [mohiva/play-silhouette#510]
But the main version is 4.0.0. Is there a reason that Play Silhouette Persistence Memory has version 4.0.0-BETA4?

**Comment by akkie** [comment]
The package `play-silhouette-persistence-memory` isn't needed anymore, because it's merged into [play-silhouette-persistence](https://mvnrepository.com/artifact/com.mohiva/play-silhouette-persistence_2.11/4.0.0).
