### ISSUE TITLE
DefaultSocialStateHandler not Base64 encoding Cookies

### ISSUE THREAD

**Issue by halfhp** [mohiva/play-silhouette#511]
While trying to get the 2.6 snapshot working with `DefaultSocialStateHandler` and a `CsrfStateItemHandler` I was getting encoding exceptions when Silhouette was attempting to deserialize the csrf cookie post Oauth2 handshake.  Looking at the changelog for 2.6 I noticed that `ItemStructure.asString` was renamed `ItemStructure.asString`.  I'm not sure if this was an accident or not.

**Comment by halfhp** [comment]
I've submitted [This PR](https://github.com/mohiva/play-silhouette/pull/512) with a potential fix.

**Comment by akkie** [comment]
Thanks for reporting the issue. This was indeed a bug. Your fix was correct and the test was wrong. It had also the `asString` call missing. I've fixed it know and will publish a new snapshot version.
