### ISSUE TITLE
NoSuchMethodError: OAuth2Provider$class.getAccessToken

### ISSUE THREAD

**Issue by halfhp** [mohiva/play-silhouette#518]
After updating to the official Play 2.6 release I get the following exception:

> Exception in thread "ForkJoinPool-1-worker-3" java.lang.NoSuchMethodError: play.api.libs.ws.BodyWritable$.writeableOf_urlEncodedForm()Lplay/api/libs/ws/BodyWritable;
> 	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.getAccessToken(OAuth2Provider.scala:232)
> 	at com.mohiva.play.silhouette.impl.providers.oauth2.GitHubProvider.getAccessToken(GitHubProvider.scala:117)
> 	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$authenticate$2$$anonfun$apply$2.apply(OAuth2Provider.scala:108)
> 	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$authenticate$2$$anonfun$apply$2.apply(OAuth2Provider.scala:107)
> 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
> 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
> 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
> 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

I'm also using the latest 2.6 snapshot of Silhouette.

I've not had a chance (and likely wont) to dig into the the root cause but seems like its just a matter of a method name change or removal in the final release version of Play 2.6

**Comment by akkie** [comment]
Thanks for reporting this. I'll release a RC1 based on the final 2.6 version at the end of the week.

**Comment by akkie** [comment]
@halfhp Could you please test again with the latest snapshot?

**Comment by halfhp** [comment]
appears to be working - thx

**Comment by akkie** [comment]
Great! Thanks :+1:
