### ISSUE TITLE
JWTAuthenticatorSettings: Cannot generate a config value reader when migrating to 5.0.0-RC2

### ISSUE THREAD

**Issue by epot** [mohiva/play-silhouette#525]
Hello,

I tried to migrate the following method from silhouette 4 to 5:

    @Provides
    def provideAuthenticatorService(
      @Named("authenticator-crypter") crypter: Crypter,
      idGenerator: IDGenerator,
      configuration: Configuration,
      clock: Clock): AuthenticatorService[JWTAuthenticator] = {
  
      val config = configuration.underlying.as[JWTAuthenticatorSettings]("silhouette.authenticator")
      val encoder = new CrypterAuthenticatorEncoder(crypter)
  
      new JWTAuthenticatorService(config, None, encoder, idGenerator, clock)
    }

But I get the following error:

    Cannot generate a config value reader for type Option[Option[Seq[com.mohiva.play.silhouette.api.util.RequestPart.Value]]], because value readers cannot be auto-generated for types with type parameters. Consider defining your own ValueReader[Option[Option[Seq[com.mohiva.play.silhouette.api.util.RequestPart.Value]]]]

Any idea?

**Comment by akkie** [comment]
https://github.com/mohiva/play-silhouette/blob/master/.github/ISSUE_TEMPLATE.md

> This is an issue tracker, used to manage and track the development of Silhouette. It is not a support system and so it is not a place to ask questions or get help. If you're not sure if you have found a bug, the best place to start is with either the [forum] or [Gitter channel]. If you have a feature request, the [forum] is better than the issue tracker to discuss it.

[forum]: http://discourse.silhouette.rocks/
[Gitter channel]: https://gitter.im/mohiva/play-silhouette

**Comment by epot** [comment]
Oops, sorry. I posted on the forum :).
