### ISSUE TITLE
play 2.6.13 logging conflicts with dependencies built against earlier versions

### ISSUE THREAD

**Issue by Enalmada** [mohiva/play-silhouette#538]
play [2.6.13](https://discuss.lightbend.com/t/play-2-6-13-released/629) made a change to logging that is conflicting with a [bug](https://github.com/playframework/playframework/issues/8124) in the version of play that silhouette is currently built with.  The only way silhouette users can safely update their projects to 2.6.13 is if silhouette dependency is updated first.  Unfortunately any silhouette users that happen to update their play version to 2.6.13 with current version of silhouette will have severe logging issues that are not easy to triage.  (More info about this in the 2.6.13 release notes forum linked above)

**Comment by richdougherty** [comment]
The play issue for this is here: https://github.com/playframework/playframework/issues/8361

**Comment by akkie** [comment]
I've just released version 5.0.4 which contains the updated dependencies
