### ISSUE TITLE
5.0.5 SameSite upgrade issue

### ISSUE THREAD

**Issue by Enalmada** [mohiva/play-silhouette#543]
When upgrading from 5.0.4 to 5.0.5, I get two compile errors in SilhouetteModule:

> Cannot generate a config value reader for type Option[Option[play.api.mvc.Cookie.SameSite]], because value readers cannot be auto-generated for types with type parameters. Consider defining your own ValueReader[Option[Option[play.api.mvc.Cookie.SameSite]]]
> [error]     val config = configuration.underlying.as[CookieAuthenticatorSettings]("silhouette.authenticator")

> Cannot generate a config value reader for type Option[Option[play.api.mvc.Cookie.SameSite]], because value readers cannot be auto-generated for types with type parameters. Consider defining your own ValueReader[Option[Option[play.api.mvc.Cookie.SameSite]]]
> [error]     val settings = configuration.underlying.as[CookieSecretSettings]("silhouette.oauth1TokenSecretProvider")

I am assuming the compile error is because ficus can't do "configuration.underlying.as" on objects with complex types.  I suspect either Cookie.SameSite should probably be a string so we can override it in silhouette.conf.    Or if you want it to stay as is, can you please update play-silhouette-seed to 5.0.5 so users can see how SilhouetteModule should work with the new version?

**Comment by akkie** [comment]
Please read https://github.com/mohiva/play-silhouette/pull/541#issuecomment-395357916

**Comment by dominics** [comment]
Linking to the Cookie.SameSite ValueReader implementation in play-silhouette-seed, because that's what most people reading this issue will probably be interested in: https://github.com/mohiva/play-silhouette-seed/pull/105/commits/4afdd1d1573eb968c8894b11da039f3036a10ff8

**Comment by nafg** [comment]
@dominics that is overly verbose, this suffices:

```scala
implicit val sameSiteReader: ValueReader[Option[Cookie.SameSite]] =
    ValueReader.relative(cfg => Cookie.SameSite.parse(cfg.as[String]))
```
