### ISSUE TITLE
GoogleProvider to switch to new Google People API

### ISSUE THREAD

**Issue by mheuer** [mohiva/play-silhouette#548]
Google is retiring the Google+ APIs starting in Jan 2019 as part of the wider Google+ shutdown. Today we use the Google+ API retrieve the user profile information (https://www.googleapis.com/plus/v1/people/me). That needs to be updated to use the regular People API (https://people.googleapis.com/v1/people/me). 
An alternative would be the basic user info from the sign-in API (https://www.googleapis.com/oauth2/v2/userinfo), but that does not contain any information about the user avatar image if it is a default image or actual user supplied image. Hence the use of the People API.

No changes to the authentication process. The OAuth2 implicit grant flows will continue to work as today.

**Comment by mheuer** [comment]
Starting dev work to switch the API. Expect a PR in a couple of days.

**Comment by akkie** [comment]
Will release a snapshot version in a few days

**Comment by mheuer** [comment]
Thanks! Any timeline for a full release? I am trying to get this API switched as soon as I can. But hesitant to do too many workarounds if there is a release in the next week or so.

**Comment by akkie** [comment]
By the end of the week at the latest.

**Comment by akkie** [comment]
@mheuer 5.0.7 is out
