### ISSUE TITLE
Support for Google TOTP 2-Factor authentication

### ISSUE THREAD

**Issue by bravegag** [mohiva/play-silhouette#555]
Is there support for Google TOTP already? if not, can someone point me to directions where to look to integrate it? by this I mean the silhouette idiomatic way to add such extensions.

I have a reference in another seed: 
https://github.com/bravegag/play-authenticate-usage-scala

that uses: 
https://github.com/wstrange/GoogleAuth

**Comment by akkie** [comment]
This would be a good addition. In Silhouette you would create a new provider. A pull request is welcome.

**Comment by bravegag** [comment]
Hi @akkie, we have the PR ready to merge .. please let us (@dloshkarev) know if there is anything you need from us.
Cheers!

**Comment by akkie** [comment]
@bravegag I'm away from home this week. I'll take a look at it next week.

**Comment by akkie** [comment]
Fixed with #557
