### ISSUE TITLE
Support for Sudo actions?

### ISSUE THREAD

**Issue by bravegag** [mohiva/play-silhouette#556]
Is there already support for "sudo" actions? Sudo actions are the ones that typically re-ask the user for password even though he/she has already been authenticated with a cookie. They are useful to ensure authentication when the user attempts to modify or view sensitive information such as: billing, account security, etc.

**Comment by akkie** [comment]
Hi,

Thanks for your interest in Silhouette. As stated in the [readme](https://github.com/mohiva/play-silhouette#support), the issue tracker is for issues only. For questions please use the forum or the chat.

Best regards,
Christian
