### ISSUE TITLE
Refactor AuthInfo derived case classes to traits in api

### ISSUE THREAD

**Issue by bravegag** [mohiva/play-silhouette#559]
I'd like to propose refactoring `AuthInfo` derived case classes e.g. `LoginInfo` to traits in api and core and while at it, make it also camel-case convention compliant i.e. `providerId` instead of `providerID` take into account the Slick code generator that doesn't support exceptions like `providerID` etc. The refactoring would be straightforward:

from
```
case class LoginInfo(providerID: String, providerKey: String)
```
to
```
trait LoginInfo extends AuthInfo {
    val providerId: String
    val providerKey: String
}
```
and also straightforward to provide the needed default implementation:
```
case class LoginInfoImpl(
    override val providerId: String,
    override val providerKey: String
) extends LoginInfo
```

The reason being to make silhouette more friendly to different persistence implementations, for example, when using Slick it would be miles away simpler to seamlessly plug in into Silhouette a concrete `LoginInfoRow` implementation that can be Slick-mapped to the database: 

```
  /**
   * Entity class storing rows of table LoginInfo.
   * @param id Database column id SqlType(INT), AutoInc, PrimaryKey
   * @param providerId Database column provider_id SqlType(VARCHAR), Length(100,true)
   * @param providerKey Database column provider_key SqlType(VARCHAR), Length(50,true)
   * @param modified Database column modified SqlType(TIMESTAMP), Default(None)
   */
  case class LoginInfoRow(id: Int, override val providerId: String, override val providerKey: String, modified: Option[java.sql.Timestamp] = None) extends com.mohiva.play.silhouette.api.LoginInfo
  /** GetResult implicit for fetching LoginInfoRow objects using plain SQL queries */
  implicit def GetResultLoginInfoRow(implicit e0: GR[Int], e1: GR[String], e2: GR[Option[java.sql.Timestamp]]): GR[LoginInfoRow] = GR {
    prs =>
      import prs._
      LoginInfoRow.tupled((<<[Int], <<[String], <<[String], <<?[java.sql.Timestamp]))
  }
  /** Table description of table login_info. Objects of this class serve as prototypes for rows in queries. */
  class LoginInfo(_tableTag: Tag) extends profile.api.Table[LoginInfoRow](_tableTag, Some("myappdb"), "login_info") {
    def * = (id, providerId, providerKey, modified) <> (LoginInfoRow.tupled, LoginInfoRow.unapply)
    /** Maps whole row to an option. Useful for outer joins. */
    def ? = ((Rep.Some(id), Rep.Some(providerId), Rep.Some(providerKey), modified)).shaped.<>({ r => import r._; _1.map(_ => LoginInfoRow.tupled((_1.get, _2.get, _3.get, _4))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))

    /** Database column id SqlType(INT), AutoInc, PrimaryKey */
    val id: Rep[Int] = column[Int]("id", O.AutoInc, O.PrimaryKey)
    /** Database column provider_id SqlType(VARCHAR), Length(100,true) */
    val providerId: Rep[String] = column[String]("provider_id", O.Length(100, varying = true))
    /** Database column provider_key SqlType(VARCHAR), Length(50,true) */
    val providerKey: Rep[String] = column[String]("provider_key", O.Length(50, varying = true))
    /** Database column modified SqlType(TIMESTAMP), Default(None) */
    val modified: Rep[Option[java.sql.Timestamp]] = column[Option[java.sql.Timestamp]]("modified", O.Default(None))

    /** Index over (providerId) (database name idx_provider_id) */
    val index1 = index("idx_provider_id", providerId)
    /** Index over (providerKey) (database name idx_provider_key) */
    val index2 = index("idx_provider_key", providerKey)
  }
  /** Collection-like TableQuery object for table LoginInfo */
  lazy val LoginInfo = new TableQuery(tag => new LoginInfo(tag))
```

With the current case-class approach it not possible because Scala 2.12.x doesn't allow case class inheritance. The only solution left now would be converting between two parallel case classes and this would be complex, very involved, inefficient and error-prone. With the proposed approach it would only require inheriting from the corresponding `*Info` trait.

If this is approved I will be happy to make a PR and have a Seed with Slick implementations for MySQL and Postgres. 

See this SO post here:
https://stackoverflow.com/questions/56303882/how-to-override-a-case-class-attribute-and-avoid-duplicated-storage

**Comment by akkie** [comment]
@bravegag This is easily feasible with implicit or explicit conversions. Please see my SO answer. I don't think a change isn't needed.

**Comment by bravegag** [comment]
@akkie see my comments in SO I think it still makes a lot of sense to make the refactoring to traits and it will not incur in any migration overhead for existing Silhouette projects.

**Comment by akkie** [comment]
From the library perspective there is only one `LoginInfo`. It's a type that fits exactly one purpose, namely representing a login for a provider. So from a logical standpoint, there is no requirement to define it as trait. There cannot be different implementations.

I see your point that it would make your use case easier, but keep in mind that there are also other use cases. It's also a matter of style. I see your Slick specific datatype as a completely different datatype. Both types share the same data, but in a completely different context.

You say that it wouldn't have impact on existing code. I see it differently. Pattern matching with the compiler created unapply method isn't possible anymore. There is also a lot of code around that uses automatic type class derivation for JSON.

From your SO comment:
> Remember I’d need to also have fromSilhouette equivalents and have those implicit and conversions affecting my whole App when there is no need to if those AuthInfo were traits.

Mostly Silhouette core code creates `LoginInfo` instances. So it's regardless of whether the current or the trait based approach will be used. You need always a way to transform this type into your database specific type.

I think my suggested approach is a valid approach which will work excellent to solve your use case. I have also worked with Slick before. If I remember correctly you can define your class in the following way and adapt your converter to use this approach. See `LoginInfo` as completely independent type like `Int` or `java.sql.Timestamp`.

```
case class LoginInfoRow(
  id: Int,
  loginInfo: LoginInfo,
  modified: Option[java.sql.Timestamp] = None
)
```

**Comment by bravegag** [comment]
@akkie thanks a lot for taking the time to look into this! I see your points and also realized it wouldn't be so straightforward to do this refactoring so better to use the solution you proposed. Cheers!
