### ISSUE TITLE
Upgrade to Play 2.7.2

### ISSUE THREAD

**Issue by bravegag** [mohiva/play-silhouette#563]
It would be great bumping the dependencies and upgrading to Play 2.7.2. 

Simple changes here:
https://github.com/bravegag/play-silhouette/commit/01951de1a09e0c62c039ec044fc9656f3aae812c

Sorry can't do PR because already lost the clean master state on my Fork.

**Comment by akkie** [comment]
Done and released with 6.0.0

**Comment by bravegag** [comment]
@akkie fantastic! thanks! how about the other PRs? :) I can help if needed. We can telco on Skype to walk you throught the 2FA GoogleAuth one.
